boot/config.js, components/mediaSelector.html, components/mediaSelector.js, components/themeSelector.css, components/themeSelector.html, components/themeSelector.js, components/visualSelector.css, components/visualSelector.html, components/visualSelector.js, services/details.js
Deleted previous fork and recreated fork with modified files.
=> New Fork with Updates

components/userAuthentication.css, components/userAuthentication.html, components/userAuthentication.js, components/userAuthentication.less
some bugs fixed in this PR:
- Angular fields shouldn't have duplicate titles
- Show a progress bar & hide button after each time user hit a button (sign in, sign up, etc)
- Code improvement.
=> various bugs fixes

boot/config.js, components/stream.html, components/stream.js, components/streamExcerpt.css, components/streamExcerpt.html, components/streamExcerpt.js, components/streamExcerpt.less
It just the template for now. I create follow the [demo](http://demo.sitetheory.net/Daniela-s-Fancy-Clothes)
=> create stream and streamExcerpt components

boot/config.js, controllers/utilities.js, services/commonMethods.js, services/model.js
https://app.asana.com/0/348819471518170/519151957556985/f
=> Request specific content version

components/tag.html, components/tag.js
https://app.asana.com/0/348819471518170/526308451457530/f
=> show tags dropdown

components/pagination.css, components/pagination.html, components/pagination.js, controllers/filterContentType.js, services/collection.js, services/commonMethods.js
https://app.asana.com/0/0/539887475257171/f
=> Reset pagination Page count whenever a new filter/search is made

services/model.js
https://app.asana.com/0/0/539887475257176/f
=> update model data change status

services/model.js
https://app.asana.com/0/0/539887475257176/f
=> change save button color when the data is changing.

services/commonMethods.js, services/model.js
https://app.asana.com/0/348819471518170/547497378287714/f
=> adjust the URL of the specific content and the sublink

components/singleSignOn.css, components/singleSignOn.html, components/singleSignOn.less
https://app.asana.com/0/348819471518170/566688583293914/f
=> remove redundant icon of social sign-on

controllers/productFilter.js
https://app.asana.com/0/348819471518170/573652136290602/f
=> fix Maximum call stack size exceeded at filter

controllers/userFilter.js
https://app.asana.com/0/348819471518170/517745057081627/f
=> check member status

components/selector.html
https://app.asana.com/0/348819471518170/590830255413886/f
=> fix show assets is selected on product page

components/help.css, components/help.html, components/help.less, controllers/generic.js, directives/edit.html, directives/edit.js
- Improve help icon
- Edit & save menu title
- Content type cannot be saved
- Handling data before displaying in DOM
- Saving both URL or Content Type
=> Some fixes for aerial menu

components/selector.js, components/userAuthentication.js, controllers/productFilter.js, services/commonMethods.js
https://app.asana.com/0/596117517607240/596115480727319/f
=> add data-api options for request

controllers/userFilter.js
https://app.asana.com/0/596117517607240/630985299129798/f
=> refactor get roles for role filter on member list page

components/mediaLibrary.html
- Remove lazy loading for thumbnails of videos
=> Remove lazy loading for thumbnails of videos

controllers/productFilter.js
=> Refactor product filter

controllers/invoiceProductFilter.js
https://app.asana.com/0/596117517607240/670447330083681/f
=> Adjust subscription filter by data range

components/mediaDetails.html, components/mediaLibrary.html, components/mediaUploader.html
fixed 
[[Media][List] The Media Component displays timestamp incorrectly#1](https://app.asana.com/0/348819471518170/691139516722657/f)
[[Media][Tag] Unable to Add Tag on Video Upload.](https://app.asana.com/0/348819471518170/689134124443343/f)
[[Media][Tag] Unable to see added tags to the media](https://app.asana.com/0/348819471518170/766630702153528/f)
[[Media][Tag] Unable to Add Multiple Tags](https://app.asana.com/0/348819471518170/756437619616609/f)
=> fixed media bugs

components/mediaLibrary.html, components/mediaLibrary.less
- CSS changes to differentiate which media(s) have been selected
- Asana task ref. id: https://app.asana.com/0/348819471518170/775811559015287/f
=> [Media][Selector] - Fixed UI issue to differentiate selected media in list

components/mediaLibrary.html, components/mediaLibrary.js, components/mediaUploader.js
Client-side condition to check whether thumbnail for Vimeo has already been generated or not. If the thumbnail is not generated then it will call Vimeo's public API to fetch the thumbnail.
=> Changes for generating thumbnails for vimeo video using API

components/mediaLibrary.html
Asana task for reference: https://app.asana.com/0/348819471518170/698205885199290/f
=> Review point changes suggested by Chadwick to update the message when no media found.

components/mediaDetails.js, components/mediaLibrary.js, components/mediaUploader.html, components/mediaUploader.js, services/media.js
Fixed issue to accept multiple formats for vimeo video and changes to show thumbnail in media uploader dialog box right after uploading a video. Asana task for reference: https://app.asana.com/0/348819471518170/815893541301690/f
=> Media upload bug fix

directives/editInline.js
[[Content][Routing] Save the route when you create a new Content (and manually set a route)](https://app.asana.com/0/596117517607240/801245171744456/f)
=> fixed custom route on article page

components/mediaDetails.html, components/mediaDetails.js, components/mediaLibrary.html, components/mediaLibrary.js, components/mediaUploader.html, components/mediaUploader.js, components/mediaUploader.less, directives/validateUrl.js, services/media.js
1. Show thumbnails at bottom of media uploader popup right after uploading of video finished
2. Update Video URL Field to be `url` (Ref: https://app.asana.com/0/348819471518170/849122527963020/f)
3. Allow user to enter valid embed code (Ref: https://app.asana.com/0/348819471518170/830500668488615/f)
4. Remove service dropdown for "youtube/vimeo" and add toggle for "URL/Embed". Service type will be detected from url itself. (Ref: https://app.asana.com/0/348819471518170/830500668488615/f)
5. Fixed issue of showing confirmation dialog of unsaved data for multiple videos (Ref: https://app.asana.com/0/348819471518170/830500668488614/f)
=> Several media bug fixes

controllers/selectMainRoute.js
[[Content][Routing] Fatal Error Saving New Route and Setting as Primary]
(https://app.asana.com/0/348819471518170/818073879415725/f)
[[Content][Routing] URL Validation (API and Angular)]
(https://app.asana.com/0/348819471518170/813473467769568/f)
[[Content][Routing] Make it possible to set the "home page"]
(https://app.asana.com/0/348819471518170/760977265875862/f)
[[Content][Routing] BUG: Can't delete new route just created. ]
(https://app.asana.com/0/348819471518170/809822352365348/f)
=> merged PRs

components/mediaDetails.html, components/mediaDetails.js, components/mediaLibrary.js, components/mediaUploader.html, components/mediaUploader.js, components/tag.css, components/tag.html, components/tag.js
[Make sure All Tags are Using One Component]
(https://app.asana.com/0/0/815893541301710/f)
[Make sure clicking "create new tag" actually creates tag elegantly]
(https://app.asana.com/0/0/815893541301709/f)
[If a tag is already selected, remove it from the list]
(https://app.asana.com/0/0/847484606154199/f)
[Fix "create new tag" Prompt in all Tag Components]
(https://app.asana.com/0/0/815893541301708/f)
[Make sure you cannot add same tag multiple times.]
(https://app.asana.com/0/0/865000786336925/f)
=> fixed tag related issues

components/mediaUploader.js
(Ref: https://app.asana.com/0/348819471518170/849122527963020/f)
=> Missing commit for task > [Media] Update Video URL Field to be `url`

components/mediaDetails.html, components/mediaDetails.js, components/mediaLibrary.html, components/mediaUploader.html, components/mediaUploader.js
1. [Media][Popup] Can't "Edit" Video URL in Popup Details (Ref: https://app.asana.com/0/348819471518170/824041341223926/f)
2. [Media] Update the Media Library hover for videos. (Ref: https://app.asana.com/0/348819471518170/875837231325177/f)
3. MediaDetails Popup Causes Unnecessary Refresh of Media Library Even when Nothing Was Edited (Ref: https://app.asana.com/0/0/875837231325179/f)
=> Media issue fixes:

components/mediaUploader.html
[[Media][Add Video] Tag area has two "add tag" labels.]
(https://app.asana.com/0/348819471518170/878313396719388/f)
=> removed two add tag labels on add tag area on media uploader

components/mediaLibrary.html
Asana task: https://app.asana.com/0/348819471518170/893034814166596/f
=> [Media][Library] Make double click open up the details

components/mediaDetails.js, directives/validateUrl.js
Asana task reference: https://app.asana.com/0/348819471518170/875837231325174/f
=> Regex validation for iframe to ensure that src property have valid URL.

components/mediaLibrary.html, components/mediaSelector.html, components/mediaUploader.html, components/mediaUploader.js
1. Fixed issue of handling double click event on media to open details page. Asana task reference: https://app.asana.com/0/596117517607240/893034814166596/f
2. Changes to show confirmation at the time of closing the media upload dialogue especially when file upload is in progress. Asana task reference: https://app.asana.com/0/inbox/756509222008859/762889682029351/824530405294287
=> Fixed media bugs.

components/mediaLibrary.html, components/mediaLibrary.js, components/mediaSelector.html, components/mediaUploader.html, components/mediaUploader.js
Asana task reference: https://app.asana.com/0/596117517607240/878223911326270
=> Media thumbnail bug fix

components/mediaDetails.js, directives/src.js, dist/stratus.js
Asana task reference:   https://app.asana.com/0/348819471518170/596145990756108/f
=> Fixed issue of lazy loading of media. 

components/mediaLibrary.html, components/mediaShortDetails.html
Asana task reference: https://app.asana.com/0/348819471518170/893034814166596/f
=> Fixed issue of double click on media to open the media details popup.

components/mediaLibrary.js
Asana task reference: https://app.asana.com/0/348819471518170/985231890560175/f
=> Defensive code to prevent media selector component to be broken.

directives/src.js
=> Fix Src Directive

components/mediaDetails.html, components/mediaUploader.html, components/tag.html, components/tag.js
https://app.asana.com/0/596117517607240/815893541301706
=> Tag component refactor 

boot/config.js, components/tag.html, components/tag.js, controllers/addAlias.js, controllers/addRoutingAlias.js, controllers/selectMainRoute.js, controllers/selectedLayout.js, dist/boot.js
https://app.asana.com/0/596117517607240/820360162971030
https://app.asana.com/0/596117517607240/815893541301706
=> tags and valid character url

package.json
=> Package Cleaning

components/tag.js
([Component][Tag][Bugs] Fix a few tag bugs)
=> https://app.asana.com/0/348819471518170/1117391928300018/f 

bower.json
=> Add Ng-File-Upload to Bower

README.md, docs/Angular.md, docs/AngularJS.md, docs/Thesis.md, package.json, tslint.json
=> Fix Lint, Update Docs, & Iterate Version

package.json, packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/member/details.component.ts, packages/idx/src/member/list.component.ts, packages/idx/src/member/search.component.ts, packages/idx/src/property/details-sub-section.component.ts, packages/idx/src/property/details.component.ts, packages/idx/src/property/list.component.ts, packages/idx/src/property/search.component.ts
- Added Angular/Angular Material Types or development
- Somewhat corrected the pathing of the files.
i imagine pathing might need some more love as each system can be different
=> @stratusjs/idx 0.2.1 - Type Support + Relative Pathing

gulpfile.js, packages/angularjs-extras/package.json, packages/angularjs/package.json
=> Fix Compilation

packages/angularjs-extras/package.json, packages/angularjs-extras/src/filters/isArray.js, packages/angularjs-extras/src/filters/math.js, packages/idx/package.json, packages/idx/src/property/details.classic.component.less
- quick fix for stylesheets
- updated dependencies
- add missing dependencies to @stratusjs/angularjs-extras
Not actively working on @stratusjs/angularjs-extras, so that as not been published
=> @stratusjs/idx 0.2.2

packages/runtime/.gitignore, packages/runtime/LICENSE, packages/runtime/README.md, packages/runtime/package.json, packages/runtime/src/stratus.ts, packages/runtime/tsconfig.json, packages/runtime/tslint.json
=> Fix Runtime Package

packages/boot/package.json, packages/boot/src/config.js
=> Boot 0.2.2

packages/angularjs/package.json, packages/angularjs/src/services/collection.ts, packages/angularjs/src/services/model.ts
=> Fix XHR Timing

packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/property/details.component.ts, packages/idx/src/property/list.component.html, packages/idx/src/property/list.component.ts, packages/idx/src/property/search.component.html, packages/idx/src/property/search.component.ts
- human readable MLS Status (Contingent vs Act Cont Show)
- human friendly bed/bath variable/url
- token session hotfixes and logic improvement
=> @stratusjs/idx 0.3.6-beta.0

packages/angular/package.json, packages/angular/src/selector/selector.component.ts, packages/angularjs/package.json, packages/angularjs/src/services/collection.ts, packages/angularjs/src/services/model.ts, packages/boot/package.json, packages/boot/src/env.js, packages/core/package.json, packages/core/src/datastore/modelBase.ts, packages/core/src/events/chronos.ts, packages/core/src/misc.ts
Changed:
- Model Structure (Minor)
Removed:
- Redundant Console Logics
Fixed:
- Model ChangeSet Logic
=> Model ChangeSets

packages/idx/package.json, packages/idx/src/idx.ts
* Added additional means to limit by idx Service
=> @stratusjs/idx 0.3.9-beta.1

.travis.yml
=> Add NodeJS 10, 12, & 13 Tests

package.json, packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/property/details.component.html, packages/idx/src/property/details.component.ts, packages/swiper/package.json
The travis tests don't seem to work because we don't use npm for installation (no package-lock.json file is used)
=> @stratusjs/idx 0.3.9-beta.2 @stratusjs/swiper 0.1.3

packages/angularjs-extras/package.json, packages/angularjs-extras/src/directives/stringToNumber.js, packages/idx/README.md, packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/property/details.component.html, packages/idx/src/property/details.component.ts, packages/idx/src/property/search.component.html, packages/idx/src/property/search.component.ts
* @stratusjs/angularjs-extras 0.2.7
* * Added comma option and extra functionality to stringToNumber directive
* @stratusjs/idx 0.3.9-beta.3 
* *  Allow forced cache reset
* * Updated ListPrice search options to keep commas in numbers
* * Stores integrations and contact as global Idx variables are widgets to use
* * Contact/integration attributes manually set take priority
=> @stratusjs/angularjs-extras 0.2.7  @stratusjs/idx 0.3.9-beta.4

packages/angularjs-extras/package.json, packages/angularjs-extras/src/filters/moment.js, packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/property/details.component.html, packages/idx/src/property/details.component.ts, packages/idx/src/property/list.component.html, packages/idx/src/property/list.component.less, packages/idx/src/property/list.component.ts
@stratusjs/angularjs-extras 0.3.0
* moment filter now handles the option `diff`, `from`, and `duration` to provide time differences between two Date sets
@stratusjs/idx 0.3.10
* CloseDate, OnMarketDate, ListPrice added to main details
* DaysOnMarket is generated for with the known Dates given
* Disclaimer now shows the correct time for proper auditing
=> @stratusjs/idx 0.3.10 / @stratusjs/angularjs-extras 0.3.0

package.json, packages/runtime/package.json, packages/runtime/src/stratus.ts
Added:
- Type Library for `vfile-message`
- Integrations key to Stratus.Environment
- Abstract key to Stratus.Environment for Dynamic Assignments
Changed:
- Bumped Stratus Runtime to `0.10.4`
=> Stratus Runtime 0.10.4 & Compilation Fixes

packages/idx/src/idx.ts, packages/idx/src/listTrac.ts, packages/idx/src/property/details.component.less, packages/idx/src/property/details.component.ts, packages/idx/src/property/list.component.html, packages/idx/src/property/list.component.less, packages/idx/src/property/list.component.ts
* Fixed less lint issues
* Fixed z-index problems due to being widgets
* Fixed getStreetNumber() due to lodash changes
* Fixed Google Maps embed and key saving
Not published as it's still being worked on
=> @stratusjs/idx Display issues

packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/property/details.component.html, packages/idx/src/property/details.component.ts
*  Fix contact variables
Published
=> @stratusjs/idx 0.3.12

packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/property/details-sub-section.component.html, packages/idx/src/property/details.component.html, packages/idx/src/property/details.component.ts, packages/idx/src/property/list.component.html, packages/idx/src/property/list.component.less, packages/idx/src/property/list.component.ts, packages/idx/src/property/search.component.html, packages/idx/src/property/search.component.less, packages/swiper/package.json, packages/swiper/src/carousel.component.ts
@stratusjs/swiper
* Updated Dependencies
* Fix for slides not initializing when swiper loads additional times
@stratusjs/idx
* Updated Dependencies
* Using latest swiper to fix slideshow issues
* Additional template fixes such as how to handling missing prices, white on white status names, spacing of buttons, ect
* Added more Aria labels for ADA compliance
* Fix unneeded URL search parameters
* * List removes invalid queries for 'where' or 'order' if given an array
* * Details fixes given default List query
* Added aria to Close Details Popup Button
@stratusjs/idx 0.3.14 and @stratusjs/swiper 0.1.5 published to npmjs
=> @stratusjs/idx 0.3.14 / @stratusjs/swiper 0.1.5

packages/angular/package.json, packages/angular/src/selector/selector.component.html
Added:
- Use of Lodash Getters (Flexible)
Fixed:
- Module Display Format
=> Angular [0.2.4]: Content Selector for New Module Format

packages/angularjs-extras/package.json, packages/angularjs-extras/src/directives/src.js, packages/idx/.npmignore, packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/property/details.component.html, packages/idx/src/property/details.component.ts
@stratusjs/angularjs-extras 0.3.4
* Added option fo stratus-src="false" to also disable progressive loading
@stratusjs/idx 0.3.20
* handle contactCommentVariable to make Street Address optionable
=> @stratusjs/angularjs-extras 0.3.4 @stratusjs/idx 0.3.20

packages/angularjs-extras/package.json, packages/angularjs-extras/src/filters/moment.js, packages/calendar/package.json, packages/calendar/src/customView.ts
@stratusjs/calendar 0.0.4
* Fix CustomView (restore tiering parent uid logic)
* Update Dependencies
@stratusjs/angularjs-extras 0.4.2
* Filter:moment ignore timezone changes if 'local' is requested, as it will already be local
=> @stratusjs/calendar 0.0.4 @stratusjs/angularjs-extras 0.4.2

gulpfile.js, packages/core/package.json, packages/core/src/conversion.ts, packages/runtime/package.json, packages/runtime/src/stratus.ts
=> Add TitleCase Conversion / Bump Runtime & Core

packages/core/package.json, packages/core/src/misc.ts
=> Core Misc.Patch: Array Element Removal Detection

packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/property/details.component.html, packages/idx/src/property/list.component.html
@stratusjs/idx 0.3.21
* Fix Status display on List and Details for CRMLS
* Handle OpenHouseStatus in details
* Handle missing PropertyType + PropertySubType (CRMLS sometimes doesn't have both)
* Update Dependencies
=> @stratusjs/idx 0.3.21

packages/idx/package.json, packages/idx/src/property/admin/search.filter.component.html, packages/idx/src/property/search.component.ts
@stratusjs/idx 0.3.23
* Fix search.component variable syncing on change events
=> @stratusjs/idx 0.3.23

packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/listTrac.ts, packages/idx/src/property/details.component.ts
@stratusjs/idx 0.4.0
* ListTrac enabled to chosen MLS services
=> @stratusjs/idx 0.4.0

packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/property/details.classic.component.html, packages/idx/src/property/details.classic.component.less, packages/idx/src/property/details.component.html, packages/idx/src/property/details.component.ts
@stratusjs/idx 0.4.2
* fixed templating issues
* working again with ListTrac on front end of 1.0
=> @stratusjs/idx 0.4.2

packages/idx/src/idx.ts, packages/idx/src/property/admin/search.filter.component.html, packages/idx/src/property/list.component.ts, packages/idx/src/property/search.component.html, packages/idx/src/property/search.component.ts
Customize Admin filters to be more specific fields (rather than generic field)
=> Adding support for new fields: PostalCode, AreaId

.github/workflows/nodejs.yml
=> Fix Github Action for NodeJS

packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/property/admin/search.filter.component.html, packages/idx/src/property/list.component.ts, packages/idx/src/property/search.component.ts
@stratusjs/idx 0.4.3
* fix default URL popups (no more displaying the blank MLSAreaMajor).
* Quality of Life for coders by adding human reading section for adding/editing widget fields to search
* fix service loading/saving Service on Admin
still issue with the list not accept a certain service to load
=> @stratusjs/idx 0.4.3

packages/idx/src/idx.ts, packages/idx/src/property/admin/search.filter.component.html, packages/idx/src/property/list.component.ts, packages/idx/src/property/search.component.ts
@stratusjs/idx (unable to publish)
* Fixed undefined issue with PostalCode/AreaId, added central location to add array/other items that need to be initialized (to try and prevent it again)
* Disabled Neighborhood chips as it's unsupported at the moment
* Fixed Neighborhoods not searching correctly for MLSAreaMajor
* restrict andOr to it's requested type (preparing for array searches)
=> fixes@stratusjs/idx 

packages/idx/src/idx.ts, packages/idx/src/property/admin/search.filter.component.html, packages/idx/src/property/search.component.html
-Add UnparsedAddress
-Remove AreaId
-Add hidden filter fields on front end if set in backend.
=> IDX Filtering UPdates

packages/angularjs/package.json
=> Bump AngularJS Package

packages/angularjs/src/services/collection.ts
This change was essential for media component. Asana task reference: https://app.asana.com/0/1154407311832843/1152352912170857/f
=> Modified collection.add() to allow to push model on top based on boolean flag

packages/angularjs/package.json, packages/angularjs/src/services/collection.ts, packages/angularjs/src/services/model.ts, packages/angularjs/src/services/registry.ts, packages/core/package.json, packages/core/src/misc.ts
Added:
- ModelOptions Interface
Fixed:
- AngularJS Model Patch
- Core Patch Algorithm
=> Add ModelOptions Interface & Fixed Model Patch (Saving)

packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/member/details.component.ts, packages/idx/src/member/list.component.ts, packages/idx/src/member/search.component.ts, packages/idx/src/property/details.component.ts, packages/idx/src/property/list.component.ts, packages/idx/src/property/search.component.ts
**@stratusjs/idx 0.5.0**
* Fixed data association between widget files (the widget $scopes are now given strict types)
* Refactored List, Search, and Idx service to provide strict Types and properly pass on the -correct- variable types instead of assuming what is what.
* Fixed the admin page and allowing more control of the query being passed around
* Strict Typed IdxService
* Fix variables that are suppose to be arrays (current and previously saved JSONs)
* MLSAreaMajor now does 'like' searches (no longer strict)
------
**This PR changes:**
* Strict Typed IdxService
* Fix variables that are suppose to be arrays (current and previously saved JSONs)
* MLSAreaMajor now does 'like' searches (no longer strict)
=> @stratusjs/idx 0.5.0

packages/angularjs/package.json, packages/angularjs/src/services/model.ts, packages/core/package.json, packages/core/src/misc.ts
Changed:
- Implements better Patch Algorithm
Fixed:
- Patch Arrays only showing changed elements instead of entire list
Note: For this to function at a full capacity, the new `patchArray()` algorithm needs to be complete.
=> Fix Patch (Band-Aid)

packages/angularjs/package.json, packages/angularjs/src/services/model.ts, packages/core/package.json, packages/core/src/datastore/modelBase.ts, packages/core/src/misc.ts
Added:
- [AngularJS 0.2.17] IgnoreKeys to ModelOptions
Changed:
- [AngularJS 0.2.17] Integrates New Patch Algorithm
- [Core 0.2.11] Complete Refactoring of New Patch Algorithm (Joins Patch & PatchArray Functionality)
=> Core 0.2.11 & AngularJS 0.2.17

packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/property/admin/search.filter.component.html, packages/idx/src/property/search.component.html, packages/idx/src/property/search.component.ts
@stratusjs/idx 0.5.1
* Type annotations
* "Preview Results" won't appear if there is no list widget
* Fix variableSync to allow adding variables that aren't set yet
=> @stratusjs/idx 0.5.1

packages/idx/src/property/admin/search.filter.component.html, packages/idx/src/property/details-sub-section.component.html, packages/idx/src/property/details.classic.component.html, packages/idx/src/property/details.component.html, packages/idx/src/property/list.component.less
@stratusjs/idx 
* Fix spaces being removed on minification
* default 'Preview Results' styling/hiding
=> @stratusjs/idx small fixes

packages/angular/package.json, packages/angular/src/tree/tree-dialog.component.html, packages/angular/src/tree/tree-dialog.component.ts, packages/angular/src/tree/tree-node.component.html, packages/angular/src/tree/tree-node.component.ts, packages/angular/src/tree/tree.component.scss, packages/angular/src/tree/tree.component.ts
=> Functional Tree Collapse, Tree Redraw Methods, & More

packages/idx/package.json, packages/idx/src/property/admin/search.filter.component.html, packages/idx/src/property/details.classic.component.html, packages/idx/src/property/details.component.html, packages/idx/src/property/details.component.ts, packages/idx/src/property/list.component.html, packages/idx/src/property/list.component.ts, packages/idx/src/property/search.component.ts
**@stratusjs/idx 0.5.4**
* fix stratus-src-version in property/list and property/details.classic
**@stratusjs/idx 0.5.3**
* Details displays HTML based PublicRemarks
* PublicRemarks aria-label
* Add OrderBy options 'Recently Updated' and 'Recently Sold'
**@stratusjs/idx 0.5.2**
* search.filter get a list of currently accessible IDX feeds (instead of showing all manual ones)
=> @stratusjs/idx 0.5.4

packages/angularjs/package.json, packages/angularjs/src/services/model.ts, packages/core/package.json, packages/core/src/datastore/modelBase.ts
- Core 0.2.12: ModelBase Patch, Watcher, & Change Propagation
- AngularJS 0.2.19: Fix Model Watcher, Patch, & Super Calls
=> Fix Model Watchers & Patch

packages/angularjs/package.json, packages/angularjs/src/services/model.ts, packages/core/package.json, packages/core/src/datastore/modelBase.ts
=> Basic Model AutoSave

packages/angularjs/package.json, packages/angularjs/src/services/model.ts
Adds:
- Intermediate ChangeSets (Data changed between Saves)
Fixes:
- Data loss from changes while XHR is pending
Note: This is a follow-up to PR #405
=> AngularJS 0.2.24: Add Intermediate ChangeSets

packages/angularjs/package.json, packages/angularjs/src/services/collection.ts, packages/angularjs/src/services/model.ts
**@stratusjs/angularjs 0.2.26**
* Collection marks own Models as completed (for autoSave and loading usage)
* Model init watches if already completed + watched (and can init as completed)
* Collection allows setting their models to be autoSaved and watched
=> @stratusjs/angularjs 0.2.26 Collection/Model Autosave/watcher/completed options

packages/angularjs/package.json, packages/angularjs/src/services/registry.ts
=> AngularJS 0.2.27: Fix Data-Api Attribute

packages/angularjs/package.json, packages/angularjs/src/services/model.ts
=> AngularJS 0.2.28: Block Empty PUT Payloads

packages/angular/package.json, packages/angular/src/boot.ts, packages/angular/src/selector/selector.component.ts, packages/angular/src/tree/tree-node.component.ts, packages/angular/src/tree/tree.component.ts
=> Angular 0.2.9: Fixed Selector Settings

packages/angular/package.json, packages/angular/src/selector/selector.component.html, packages/angular/src/selector/selector.component.scss, packages/angular/src/selector/selector.component.ts
=> Angular 0.2.10: Dynamic Selector Component

packages/core/src/misc.ts, packages/idx/src/idx.ts, packages/runtime/package.json, packages/runtime/src/stratus.ts
@stratusjs/runtime 0.11.0
* Re added Stratus.Internals.JsLoader()
* Added additional Typings for Stratus.Internals
* Added additional Typings for ObjectWithFunction (for use with angular.IScope) and AnyFunction
=> @stratusjs/runtime 0.11.0

packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/property/admin/search.filter.component.html, packages/idx/src/property/details.component.less, packages/idx/src/property/details.component.ts, packages/idx/src/property/list.component.less, packages/idx/src/property/list.component.ts, packages/idx/src/property/search.compact.component.html, packages/idx/src/property/search.component.html
**@stratusjs/idx 0.5.9**
* Fix mlsVariables processed (affecting MLS Names/disclaimers)
* Add CountyOrParish Search Options
* Unhide Pre Filtered Search options in search.components
* Fix search.components Advanced filters Layouts
* Add MLS logo size limits to list.component
=> @stratusjs/idx 0.5.9

packages/calendar/package.json
**@stratusjs/calendar 0.0.7**
* Update Calendar Styling
=> @stratusjs/calendar 0.0.7

packages/angular/src/app.module.ts, packages/boot/src/init.js
=> SystemJS Support

packages/angular/package.json, packages/angular/src/selector/selector.component.ts, packages/boot/package.json
Allows proper deletion with payload updates.
=> Angular 0.2.16: Fix Selector

packages/angular/package.json, packages/angular/src/selector/selector.component.ts, packages/core/package.json, packages/core/src/environment.ts
- Add Core Environment SameSite Cookie
- Better Selector Responsiveness
=> Core & Selector Improvements

LICENSE, package.json, packages/angular/LICENSE, packages/angular/package.json, packages/angularjs-extras/LICENSE, packages/angularjs-extras/package.json, packages/angularjs/LICENSE, packages/angularjs/package.json, packages/backend/LICENSE, packages/backend/package.json, packages/boot/LICENSE, packages/boot/package.json, packages/calendar/LICENSE, packages/calendar/package.json, packages/core/LICENSE, packages/core/package.json, packages/idx/LICENSE, packages/idx/package.json, packages/react/LICENSE, packages/react/package.json, packages/runtime/LICENSE, packages/runtime/package.json, packages/swiper/LICENSE, packages/swiper/package.json
=> Update LICENSE to MIT

packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/property/list.component.ts
**@stratusjs/idx 0.5.11**
* Fix Page and Order URL options on load
* Scroll to top of list on page change
* Fix typings
=> @stratusjs/idx 0.5.11

packages/angularjs-extras/package.json, packages/angularjs-extras/src/directives/src.js
Changes:
- Bump AngularJS-Extras to 0.6.3
Fixes:
- Src Directive
=> AngularJS-Extras 0.6.3: Fix Src Directive

packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/property/list.component.html, packages/idx/src/property/list.component.ts
**@stratusjs/idx 0.6.2**
* Fix skipping pages if with multiple feeds
* Fix ClosePrice display before ListPrice
* Update Price sorting to including ClosePrice first
* Allow sorting by array of options
=> @stratusjs/idx 0.6.2

packages/angularjs-extras/package.json, packages/angularjs-extras/src/directives/src.js, packages/runtime/package.json, packages/runtime/src/stratus.ts
=> Fixes for Lazy Loading

packages/angularjs-extras/package.json, packages/angularjs-extras/src/directives/src.js
=> Fix Src Directive (Complete)

packages/angularjs-extras/src/directives/src.js, packages/runtime/package.json, packages/runtime/src/stratus.ts
=> Runtime 0.11.2: Fix LoadImage()

packages/runtime/package.json, packages/runtime/src/stratus.ts
=> Runtime 0.11.3: Default to Normal Size

packages/runtime/package.json, packages/runtime/src/stratus.ts
=> Runtime 0.11.5: LoadImage() Optimizations

packages/runtime/package.json, packages/runtime/src/stratus.ts
=> Runtime 0.11.6: LoadImage() Fixes

packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/property/details.component.ts
**@stratusjs/idx 0.6.3**
* Fix property lookup cases where service given as a string
* Fix Service variables (name/disclaimer) - details.component force force service Ids as numbers
=> @stratusjs/idx 0.6.3

packages/angularjs/package.json, packages/angularjs/src/services/model.ts
=> AngularJS 0.2.34: Fix Model Error Handling

packages/angularjs-extras/src/components/jsonEditor.html, packages/angularjs-extras/src/components/jsonEditor.js, packages/boot/src/config.js
This takes the model object and puts it into a textarea string for editing, then validates before adding back to the object model.
=> Create New Stratus Component for JSON Editing/Validation 

packages/angularjs/package.json, packages/angularjs/src/services/model.ts
=> Angular 0.2.35: Model Saving Options

.gitignore, package.json, packages/angular/package.json, packages/angular/src/app.module.ts, packages/angular/src/boot.ts, packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/property/details.component.html, packages/idx/src/property/details.component.ts, packages/idx/src/property/list.component.html, packages/idx/src/property/list.component.ts, packages/map/.npmignore, packages/map/LICENSE, packages/map/README.md, packages/map/package.json, packages/map/src/map.component.html, packages/map/src/map.component.ts, packages/stripe/package.json, tsconfig.json
**@stratusjs/map 0.1.1** (published)
* Added Angular+ component to display Google Maps javascript sdk
* Add angularjs-like Watcher to check for externally provider Map Markers (syncs with Marker changes)
* Functional fitBounds of multiple Markers
**@stratusjs/angular 0.2.29** (published)
* Added Provider to `window` object
* Added Manual component of @stratusjs/map at `sa-map`
**@stratusjs/idx 0.6.4** (published)
* Added placeholders for use of @stratusjs/map and functionality for setting up map markers
=> @stratusjs/map 0.1.1 @stratusjs/angular 0.2.29 @stratusjs/idx 0.6.4

package.json, packages/angular/package.json, packages/angular/src/app.module.ts, packages/angular/src/editor/editor.component.html, packages/angular/src/editor/editor.component.scss, packages/angular/src/editor/editor.component.ts, packages/angular/src/editor/media-dialog.component.html, packages/map/src/map.component.ts
Adds:
- [Angular-Editor](https://www.npmjs.com/package/@kolkov/angular-editor)
- Media Dialog Outline
Fixes:
- Saving Glitches
- Map Component Lint
=> Add Angular-Editor & Fix Editor Saving

packages/angularjs/package.json, packages/angularjs/src/services/collection.ts, packages/angularjs/src/services/model.ts, packages/core/package.json, packages/core/src/datastore/modelBase.ts, packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/map.component.html, packages/idx/src/map.component.ts, packages/idx/src/member/details.component.ts, packages/idx/src/member/list.component.ts, packages/idx/src/member/search.component.ts, packages/idx/src/property/details.component.ts, packages/idx/src/property/list.component.html, packages/idx/src/property/list.component.ts, packages/idx/src/property/search.component.ts, packages/map/package.json, packages/map/src/map.component.ts
**@stratusjs/core 0.2.17** published
* modelBase Generic Types
**@stratusjs/angularjs 0.2.36** published
* model and collection Generic Types
**@stratusjs/map 0.2.0** published
* Fix linting issues
* Allow callback to replace all usage of Watcher (much faster too)
**@stratusjs/idx 0.7.0** published
* Strict Typed Collection + Models for easier comparison of what object the data is actually touching
* Fixed various typings causing invalid comparisons
* Moved methods to be shared between various components
* on/emit events throughout Idx components (Pub Sub Events for cross component and external data sharing)
* Map register placeholders
* Idx Map component (`<stratus-idx-map>`)
=> @stratusjs/core @stratusjs/angularjs Generic Type collection/Model + @stratusjs/idx/map

packages/idx/package.json, packages/idx/src/property/details-sub-section.component.html, packages/idx/src/property/details-sub-section.component.ts
**@stratusjs/idx 0.7.2**
* fix property/details-sub-section: "0" values need to not display https://app.asana.com/0/348823217261712/1193322961968756
* fix @stratusjs/angular dependency
=> @stratusjs/idx 0.7.2

packages/angular/package.json, packages/angular/src/editor/editor.component.ts
=> Fix Angular-Editor

.github/workflows/nodejs.yml
=> Disable Github Checks

packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/map.component.html, packages/idx/src/map.component.ts, packages/idx/src/member/list.component.html, packages/idx/src/member/list.component.ts, packages/idx/src/property/list.component.html, packages/idx/src/property/list.component.ts, packages/map/package.json, packages/map/src/map.component.ts
**@stratusjs/idx 0.7.3**
* Added Display Options
* Fix Google Maps Key registration
* Add connection to ListScope for scrolling with markers
**@stratusjs/map 0.2.1**
* Fix Processing boolean options correctly
=> @stratusjs/idx 0.7.3 @stratusjs/map 0.2.1

README.md, packages/core/src/events/eventManager.ts
=> Travis Adjustments

packages/idx/README.md, packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/map.component.html, packages/idx/src/map.component.ts, packages/idx/src/property/details.component.html, packages/idx/src/property/details.component.ts, packages/idx/src/property/list.component.ts
**@stratusjs/idx 0.7.4** published
* Add universal getGoogleMapsKey() for Idx widgets
* Add init options for idx/map (zoom controls, scrollwheel, sizing)
* Fix Idx/map to time in when to load sa-map
=> @stratusjs/idx 0.7.4

packages/angular/package.json, packages/angular/src/boot.ts, packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/map.component.html, packages/idx/src/map.component.ts, packages/idx/src/property/list.component.ts, packages/map/package.json, packages/map/src/map.component.html, packages/map/src/map.component.ts
**@stratusjs/idx 0.7.5** published
* Add on/emit events for sessionInit, searching, and searched
* Fix loading icon for idx/map
* Speed optimizations
**@stratusjs/map 0.2.2** published
* Fix loading icon for map
**@stratusjs/angular 0.2.33** published
* Add means to quick boot Angular+ with `<sa-boot>`
=> @stratusjs/idx 0.7.5 @stratusjs/map 0.2.2 @stratusjs/angular 0.2.33

packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/map.component.html, packages/idx/src/map.component.ts, packages/idx/src/member/list.component.ts, packages/idx/src/property/details.component.html, packages/idx/src/property/list.component.html, packages/idx/src/property/list.component.less, packages/idx/src/property/list.component.ts, packages/map/package.json, packages/map/src/map.component.ts
**@stratusjs/idx 0.7.6** published
* Fix Details invalid check for agent contact
* idx/list idx/map Highlight and scroll options
* idx/map add options for Map Icon and Icon on hover
**@stratusjs/map 0.2.3** published
* Add options for default and per marker icon and icon on hover
Notes: the Icon on hover isn't perfect and can sometimes stick atm
=> @stratusjs/idx 0.7.6 @stratusjs/map 0.2.3

packages/idx/package.json, packages/idx/src/property/details.classic.component.html, packages/idx/src/property/details.component.html, packages/idx/src/property/details.component.ts, packages/idx/src/property/list.component.ts
**@stratusjs/idx 0.7.8** published
* Fix subSection on Details widget (minorDetails section)
* Add option to hide variables on the Details widget with `data-details-hide-variables=string[]` / `data-hide-variables=string[]`
=> @stratusjs/idx 0.7.8

packages/angular/package.json, packages/angular/src/selector/selector.component.html, packages/angular/src/selector/selector.component.scss, packages/angular/src/selector/selector.component.ts
Adds:
- SVG Support (Flat & Dynamic)
- Empty List Template (Proper Message)
- Status Styling (Darkens Hidden Items)
=> Angular 0.2.34: Selector Improvements

packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/property/list.component.ts
**@stratusjs/idx 0.7.10** published
* Handle token errors
=> @stratusjs/idx 0.7.10

packages/idx/package.json, packages/idx/src/property/admin/search.filter.component.html, packages/idx/src/property/details.classic.component.html, packages/idx/src/property/details.component.html, packages/idx/src/property/list.component.ts, packages/idx/src/property/search.component.html
**@stratusjs/idx 0.7.14** published
* fix auto details popup on load
* handle InternetAddressDisplayYN
* All Statuses are togglable (Active+Closed at same time)
=> @stratusjs/idx 0.7.14

packages/idx/package.json, packages/idx/src/property/list.component.ts, packages/idx/src/property/search.component.ts
**@stratusjs/idx 0.7.15** published
* fix unprocessed arrays
* sort by _BestPrice
* Clear Criteria (all or just the Location/City fields)
* List only display the Disclaimer of MLS in use
=> @stratusjs/idx 0.7.15

package.json, packages/idx/package.json, packages/idx/src/map.component.ts, packages/idx/src/property/list.component.ts, packages/idx/src/property/search.component.ts, packages/map/package.json, packages/map/src/map.component.html, packages/map/src/map.component.scss, packages/map/src/map.component.ts
**stratusjs**
* standardize yarn requirements
**@stratusjs/map 0.2.4** published
* default to css sizing. size options override with inline
**@stratusjs/idx 0.7.15** published
* idx/map use new sa-map options
* BestPrice replacement (compared to ListPrice/ClosePrice)
* Add 'Status' order option (sorts by Active first, then BestPrice)
=> @stratusjs/idx 0.7.15 @stratusjs/map 0.2.4

packages/angular/package.json, packages/angular/src/app.module.ts, packages/angular/src/confirm-dialog/confirm-dialog.component.html, packages/angular/src/confirm-dialog/confirm-dialog.component.ts, packages/angular/src/selector/selector-autocomplete.component.html, packages/angular/src/selector/selector.component.ts, packages/angular/src/tree/tree-dialog.component.html, packages/angular/src/tree/tree-dialog.component.ts, packages/angular/src/tree/tree-node.component.html, packages/angular/src/tree/tree-node.component.ts, packages/angular/src/tree/tree.component.scss, packages/angular/src/tree/tree.component.ts, packages/angularjs/src/services/model.ts, packages/core/package.json
Adds:
- Confirm-Dialog Component
- Selector: AngularJS AutoComplete Style
- Tree: Dynamic SVG Support
- Tree: Expand & Collapse (New Method without Drop Conflict)
- Tree: Status Styling
- Tree-Dialog: AutoComplete Selected Route Display
- Tree-Dialog: AutoComplete Selected as First Element
- Tree-Dialog: AutoComplete Selected Highlight
- Tree-Dialog: AutoComplete Styling (SVGs, etc)
- Tree-Dialog: Deletion with Confirm-Dialog
- Tree-Dialog SVG Icons
- Tree-Dialog Status Button
Changes:
- Bump Core to 0.2.18 (republish `eventManager.ts`)
- `ChangeDetectionStrategy` to Default
Removes:
- Tree-Dialog: Route Display
Fixes:
- Tree-Dialog: Multiple SVG Calls
=> Angular 0.2.37: Tree Improvements

package.json, packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/map.component.html, packages/idx/src/map.component.ts, packages/idx/src/property/details.component.html, packages/idx/src/property/search.component.html, packages/map/package.json, packages/map/src/map.component.ts
**@stratusjs/map 0.3.0** published
* full page height sizing and options
**@stratusjs/idx 0.8.0-alpha.0** published
* map updated to use latest sa-map options
* added missing but used Types
* property/details fixed logic gates and bindings
* property/search removed --> and border-default (caused visual artifacts)
I don't believe the list page has exactly what was meant to yet. The idx package was published with a alpha version and not expecting to release on Sitetheory yet as it may have unintended side effects.
=> @stratusjs/map 0.3.0 @stratusjs/idx 0.8.0-alpha.0

.travis.yml, packages/angular/package.json, packages/angular/src/editor/editor.component.ts, packages/angular/src/tree/tree-dialog.component.html, packages/angular/src/tree/tree-node.component.html, packages/angular/src/tree/tree-node.component.ts, packages/angular/src/tree/tree.component.html, packages/angular/src/tree/tree.component.scss
Adds:
- Tree-Node: Dynamic SVG Support
- Tree-Node: Content Display
- Tree-Node: Proper Styling
Changes:
- Editor: Enables Sanitization
- Tree-Dialog: Content is not visible until rendered
- Travis: Latest Node Support
=> Angular 0.2.38: Tree Improvements

packages/angular/package.json, packages/angular/src/editor/editor.component.html, packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/property/admin/search.filter.component.html, packages/idx/src/property/list.component.ts, packages/idx/src/property/search.component.ts
**@stratusjs/idx 0.8.1** published
* fixed simple fix for non-object json syncing variables
* fixed Order not saving on the Url
**@stratusjs/angular 0.2.39** published
* fixed angular editor fix duplicate id errors
=> @stratusjs/idx 0.8.1 @stratusjs/angular 0.2.39

packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/property/details.component.ts
**@stratusjs/idx 0.8.2** published
* GoogleMaps variable changed to `publicKey`
=> @stratusjs/idx 0.8.2

packages/angularjs/package.json, packages/angularjs/src/services/model.ts
=> AngularJS 0.2.38: Model Events

gulpfile.js, packages/angular/package.json, packages/angular/src/tree/tree-node.component.html, packages/angular/src/tree/tree.component.html, packages/angular/src/tree/tree.component.ts
Adds:
- CSS Source Maps
- Tree: Custom Sorting (Disabled CDK Sort)
- Tree: Improved Debug Information
Fixes:
- Tree: Child Sorting
=> Angular 0.2.40: Tree Improvements

.travis.yml
=> Fix Travis Node Version

packages/angular/package.json, packages/angular/src/editor/editor.component.ts
Changes:
- Editor: Disable Sanitizer
=> Angular 0.2.41: Fix Angular-Editor

.stylelintrc, packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/map.component.ts, packages/idx/src/property/admin/search.filter.component.html, packages/idx/src/property/search.compact.component.html, packages/idx/src/property/search.component.html, packages/idx/src/property/search.component.ts
**@stratusjs/idx 0.8.3** published
* OpenHouseOnly option
* Admin Auto IDX select if only option
* Temp fix for Sort options not retaining an array (Status)
* Fix scss linting
* Sort menu onClick rather than onHover
* Update list image shapeholder
=> @stratusjs/idx 0.8.3

packages/angularjs/package.json, packages/angularjs/src/services/collection.ts
Changes:
- Collection.Add(): Returns Model
=> AngularJS 0.2.39: Collection.Add() Return

packages/angularjs/package.json, packages/angularjs/src/services/collection.ts
Adds:
- Collection.Add(): Strict Options
Fixes:
- Collection.Add(): Model Initialization
- Collection.Add(): Model AutoSave
=> AngularJS 0.2.40: Collection Improvements

packages/angularjs/package.json
=> Fix Angular-Material Dialogs

packages/angularjs/package.json, packages/angularjs/src/services/collection.ts
Fixes:
- Collection.Add() Save, Watch, & AutoSave Logic
=> AngularJS 0.2.45: Fix Collection.Add()

gulpfile.js, packages/angularjs/package.json, packages/angularjs/src/controllers/generic.ts, packages/angularjs/src/services/model.ts, packages/angularjs/src/services/registry.ts, packages/core/src/datastore/modelBase.ts
Adds:
- Controller: Redraw for all Change Events
- Model: Event Change Trigger on Destroy()
- Registry: Strict Typing
- Registry: Toggle for `data-fetch`
Changes:
- Model: Persisted Patches only after Successful Fetch
=> AngularJS 0.2.46: Optimization & Stabilization

packages/angular/package.json, packages/angular/src/editor/editor.component.ts, packages/angular/src/tree/tree-dialog.component.ts
Adds:
- Editor: Image Sizing Normalization
Changes:
- Tree: Content Selector Query
Removes:
- Editor: Video Insert
=> Angular 0.2.48: Critical Issues

packages/angularjs/package.json, packages/angularjs/src/services/model.ts
Adds:
- Model: `serviceId` Option
=> AngularJS 0.2.48: Add Model Options

.stylelintrc, packages/idx/package.json, packages/idx/src/property/details.component.ts, packages/idx/src/property/list.component.ts, packages/idx/src/property/search.component.html, packages/idx/src/property/search.component.less
**@stratusjs/idx 0.9.0** published
* Prevent OpenHouseOnly option when required items aren't present
* Search z-index covering map fix
* Css linting fixes
* Clean up
=> @stratusjs/idx 0.9.0

gulpfile.ts, package.json, packages/angular/package.json, packages/angular/src/editor/editor.component.ts, packages/angular/src/froala/editor/froala-editor.directive.ts, packages/angular/src/froala/plugins/image_manager.ts
Adds:
- Editor: Froala Implementation
Fixes:
- Froala Configs now load
- Unstable Plugins are disabled
=> Angular 0.2.51: Froala Implementation

packages/idx/package.json, packages/idx/src/property/details.component.less, packages/idx/src/property/list.component.less
**@stratusjs/idx 0.9.2** published
* fix disclaimer logo
=> @stratusjs/idx 0.9.2 fix disclaimer logo

packages/angular/package.json, packages/angular/src/app.module.ts, packages/angular/src/editor/editor.component.html, packages/angular/src/editor/editor.component.scss, packages/angular/src/editor/editor.component.ts, packages/angular/src/editor/media-dialog.component.html, packages/angular/src/editor/media-dialog.component.ts, packages/angular/src/froala/plugins/mediaManager.ts
Adds:
- Editor: Plugin Lifecyle
- Editor: Media-Dialog Plugin Lifecycle
- Froala: Media Manager Plugin Lifecycle
Fixes:
- Froala: Sticky Toolbar in MD-Tabs
- Froala: Media Manager insert on caret
=> Angular 0.2.54: Froala Media Manager

.gitignore, packages/angular/package.json, packages/angular/src/editor/editor.component.scss, packages/angular/src/editor/editor.component.ts, packages/angular/src/editor/media-dialog.component.html, packages/angular/src/editor/media-dialog.component.ts, packages/angular/src/froala/plugins/mediaManager.ts
Adds:
- Editor: Handling for img tags with base64 data
- Froala: Paste Uploads Images
- Froala: Font & Style Config
- Froala: Remote Image Uploads
- Froala: Tag Filters
- Media-Dialog: Snackbar Messages
- Media-Dialog: Embedly Support
- Media-Dialog: Direct Link Support
- Media-Dialog: Video Support (URL & Embed)
- Media-Dialog: Audio Support
- Media-Dialog: PDF Support
- Media-Dialog: Doc Support
- Media-Dialog: Vimeo Thumbnail Support
- Media-Dialog: Youtube Thumbnail Support
- Media-Dialog: Video Text Fallback
Fixes:
- Froala: Catastrophic Pastes (Inserting Images created base64 data and overloaded the system)
- Froala: Z-Index (Quick Insert, Table, & Media Edit Dialogs previously appeared behind the editor)
=> Angular 0.2.56: Editor, Media Dialog, Froala, & Froala Paste Functionality

packages/angular/package.json, packages/angular/src/app.module.ts, packages/angular/src/editor/editor.component.ts, packages/angular/src/editor/media-dialog.component.html, packages/angular/src/editor/media-dialog.component.scss, packages/angular/src/editor/media-dialog.component.ts, packages/angular/src/tree/tree.component.ts
Adds:
- Angular: Flex Layout
- Media-Dialog: Flex Layout with Cards
- Media-Dialog: Media Information
Changes:
- Editor: Froala Config (Plugins & Toolbar)
- Media-Dialog: Prioritize `Media.Embed`
- Media-Dialog: Better Audio Control Fallback
- Tree: Default to expanded
Fixes:
- Froala: Several Plugins
=> Angular 0.2.57: Froala, Layouts, & Tree

packages/angular/package.json, packages/angular/src/editor/editor.component.ts
=> Angular 0.2.58: Fix Froala Rich Paste

packages/core/package.json, packages/core/src/environment.ts
Changes:
- Cookie `SameSite` default to `Lax`
=> Core 0.2.19: Fix Cookie Security

gulpfile.ts, packages/angular/package.json, packages/angular/src/editor/editor.component.ts, packages/angular/src/editor/media-dialog.component.html, packages/angular/src/froala/plugins/mediaManager.ts, packages/angular/src/tree/tree-dialog.component.html, packages/angular/src/tree/tree-node.component.html
Adds:
- Gulpfile: `compressCSS` command
- Gulpfile: `compressJavaScript` command
- Gulpfile: `compressTemplate` command
- Media-Dialog: Card Action Buttons
- Media-Dialog: Informational Tooltips
- Media-Dialog: Name Truncation
Changes:
- Froala: MediaManager Title
- Froala: Toolbar Configuration
Removes:
- Froala: Spell Checker
Fixes:
- Tree: Route & Title Information
- Tree & Editor: Several Catastrophic Errors
=> Angular 0.2.59: Editor & Tree Improvements

packages/angular/package.json, packages/angular/src/editor/editor.component.ts
Changes:
- Froala: Disable HTML Tag Removal
=> Angular 0.2.61: Editor Improvements

packages/angularjs/package.json, packages/angularjs/src/services/collection.ts
=> AngularJS 0.2.49: Add Collection.Map()

packages/angular/package.json, packages/angular/src/editor/editor.component.ts, packages/angular/src/tree/tree-dialog.component.html, packages/angular/src/tree/tree-dialog.component.ts, packages/angular/src/tree/tree-node.component.ts
Adds:
- Editor: All SVG Tags to Whitelist
- Tree: Browser Target Field
=> Angular 0.2.62: Editor & Tree Improvements

packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/property/admin/search.filter.component.html, packages/idx/src/property/search.compact.component.html, packages/idx/src/property/search.component.html, packages/map/package.json
**@stratusjs/idx 0.9.7** published
* Add options for OfficeNumber searching, similar to AgentLicense
=> @stratusjs/idx 0.9.7

packages/idx/package.json, packages/idx/src/property/admin/search.filter.component.less, packages/idx/src/property/details.classic.component.html, packages/idx/src/property/details.classic.component.less, packages/idx/src/property/details.component.html, packages/idx/src/property/search.classic.component.html, packages/idx/src/property/search.classic.component.less, packages/idx/src/property/search.compact.component.less, packages/idx/src/property/search.component.html
**@stratusjs/idx 0.10.1** published
* property/details
* * Add AgentNumber if no license provided
* * Add Open House for MLS requirements
* * Fix Human readable LivingArea
* * Classic Template: Fix no details spacing on specs
* * Classic Template: Fix disclaimer display
* property/search
* * Fix office-number font display
* * Classic Template: Add missing "Open Houses Only" option
=> @stratusjs/idx 0.10.1 

packages/angularjs/package.json, packages/angularjs/src/services/collection.ts, packages/core/src/datastore/modelBase.ts, packages/runtime/src/stratus.ts
=> AngularJS 0.2.50: Collection Add Event

packages/idx/package.json, packages/idx/src/property/details.classic.component.html
**@stratusjs/idx 0.10.2** published
* Fixed: property/details.classic Closed Date spacing
=> @stratusjs/idx 0.10.2

packages/calendar/package.json, packages/calendar/src/calendar.ts, packages/idx/package.json
**@stratusjs/calendar 0.0.8** published
* Fix: remove broken cors-anywhere.herokuapp.com service
**@stratusjs/idx 0.10.3** published
* Mistakenly republish for property/details.classic fix Closed Date spacing
=> @stratusjs/idx 0.10.3 @stratusjs/calendar 0.0.8

packages/angular/package.json, packages/angular/src/editor/editor.component.ts, packages/angular/src/froala/plugins/inputButton.ts, packages/angular/src/froala/plugins/menuButton.ts
Adds:
- Editor: SVG Support
- Editor: Universal Input Button
=> Angular 0.2.66: Editor API & SVGs

packages/angular/package.json, packages/angular/src/editor/editor.component.ts
Fixes:
- Editor: Style Removal
=> Angular 0.2.67: Editor Improvements

packages/idx/package.json, packages/idx/src/property/list.component.ts, packages/idx/src/property/list.empty.component.html, packages/stripe/package.json, packages/stripe/src/payment-method-list.component.html, packages/stripe/src/payment-method-list.component.less, packages/stripe/src/payment-method-list.component.ts, packages/stripe/src/payment-method.component.html, packages/stripe/src/payment-method.component.less, packages/stripe/src/payment-method.component.ts, packages/stripe/src/setup-intent.component.ts, packages/stripe/src/stripe.ts
**@stratusjs/idx 0.10.4** published
* Added list/property options `query-service`, `query-order`, `query-per-page`, `query-where`
* Add 'empty' template for property/list
**@stratusjs/stripe 0.1.0** published
* Add @stratusjs/stripe/payment-method-list for listing off PaymentMethods
* Add @stratusjs/stripe/setup-intent for the creation, deletion, and editing of existing PaymentMethods
* Adjusted @stratusjs/stripe/payment-method to handle success and recording new records in Sitetheory
=> @stratusjs/idx 0.10.4 @stratusjs/stripe 0.1.0

packages/angular/src/selector/selector.component.html, packages/angular/src/selector/selector.component.scss
@alexgurrola NOTE: when I ran yarn test, there were errors that didn't effect my files, but could cause other issues.
[12:40:58] Finished 'compileLESS' after 766 ms
packages/angular/src/tree/tree.component.ts(41,24): error TS2307: Cannot find module '@agentepsilon/decko' or its corresponding type declarations.
packages/angularjs-extras/src/filters/numeral.ts(12,21): error TS2307: Cannot find module 'numeral' or its corresponding type declarations.
TypeScript: 2 semantic errors
TypeScript: emit succeeded (with errors)
[12:41:11] 'compileTypeScript' errored after 14 s
[12:41:11] Error: TypeScript: Compilation failed
at Output.mightFinish (/Users/chadwickmeyer/Sites/stratus/node_modules/gulp-typescript/release/output.js:130:43)
at /Users/chadwickmeyer/Sites/stratus/node_modules/gulp-typescrip …
=> Add "unpublished" flag and class to the selector.component 

packages/angular/package.json
=> Angular 0.2.68: Selector Improvements

packages/idx/package.json, packages/idx/src/disclaimer/disclaimer.component.less, packages/idx/src/disclaimer/disclaimer.component.ts, packages/idx/src/property/details.classic.component.less, packages/idx/src/property/details.component.less, packages/idx/src/property/list.component.less
** @stratusidx/idx 0.11.2** published
* stratus-idx-disclaimer styling fixes and better CSS control
=> @stratusidx/idx 0.11.2

packages/idx/package.json, packages/idx/src/map/map.component.ts, packages/idx/src/property/list.component.ts, packages/idx/src/property/search.component.html, packages/idx/src/property/search.component.ts
**@strausjs/idx 0.12.3** published
* Fix advancedFilterStatus/openStatus/advancedSearchUrl/detailsLinkTarget variable usage
* Clean Up unused bindings
* Update Documentation
=> @strausjs/idx 0.12.3

packages/idx/package.json, packages/idx/src/property/list.component.html, packages/idx/src/property/list.component.ts, packages/idx/src/property/search.component.html, packages/idx/src/property/search.component.ts
**@stratusjs/idx 0.12.4** Published
* Change property/list: better element positioning and tracking
* Change property/list: Initialization is delay further to enable dynamic element id(might be slower to start)
* Fix unclosed elements
* Add Documentation
=> @stratusjs/idx 0.12.4

packages/idx/package.json
Changes from https://github.com/Sitetheory/stratus/pull/562
=> @stratusjs/idx 0.12.6

packages/idx/package.json, packages/idx/src/property/list.component.ts
**@stratusjs/idx 0.12.7** published
* adds property/list attribute "displayOrderOptions"
* changes style property/list locations
Includes changes from https://github.com/Sitetheory/stratus/pull/569
=> @stratusjs/idx 0.12.7

packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/property/details.component.less, packages/idx/src/property/list.component.less, packages/idx/src/property/list.component.ts
**@stratusjs/idx 0.12.8** published
* fix: list collection's pending handling in one location and ignoring pending when not needed
* fix: StyleLint errors
* change: global Sitetheory styling to stratus and custom stratus styling to Sitetheory
=> @stratusjs/idx 0.12.8

packages/angularjs/package.json, packages/angularjs/src/services/model.ts
Changes:
- Model.Destroy(): handles new models
=> AngularJS 0.2.51: Model.Destroy() Improvements

.gitignore, packages/angularjs-extras/package.json, packages/angularjs-extras/src/directives/maxLength.ts
=> AngularJS-Extras 0.8.1: MaxLength Directive

packages/angularjs/src/components/base.ts, packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/member/list.component.ts, packages/idx/src/member/search.component.html, packages/idx/src/member/search.component.ts, packages/idx/src/office/list.component.html, packages/idx/src/office/list.component.ts, packages/idx/src/office/list.empty.component.html, packages/idx/src/office/search.component.ts, packages/idx/src/office/search.group-selector.component.html, packages/idx/src/office/search.group-selector.component.less, packages/idx/src/property/admin/search.filter.component.html, packages/idx/src/property/admin/search.filter.component.less, packages/idx/src/property/list.component.ts, packages/idx/src/property/search.classic.component.html, packages/idx/src/property/search.compact.component.html, packages/idx/src/property/search.component.html, packages/idx/src/property/search.component.ts
@stratusjs/idx 0.13.0 published
* Add: Office Selector (Search + List, only intended for group-selector lookup at this time)
* Add: Property Search component setup to load the Office Selector
* Add: `Idx Service`, `Member List` additional typings
* Change: Property Search (and admin) template update to use Office selection/lookups
* Change: Refactored multiple reused functions into Idx Service 
* * renamed `search<ComponentName>()` to just `search()`
* Change: Update Dependencies
@stratusjs/angularjs
* Add: Additional Base Typings
TODO
* Add changes to Stratus wiki
=> @stratusjs/idx 0.13.0 Office Selector

packages/angularjs-extras/package.json, packages/angularjs-extras/src/directives/fullHeight.ts, packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/property/admin/search.filter.component.html, packages/idx/src/property/list.component.ts, packages/idx/src/property/search.component.html, packages/idx/src/property/search.component.ts
**@stratusjs/idx 0.13.2** published
* Add: Filters to limit/search by `ListingId`
* Add: Property Search option `displayFilterFullHeight` option to enable/disable full height for this menu. Defaults to false
* Removed: Duplicate settings from #579
* Changed: Increased Office Selector Results to 100
* Fix: Adjusted angular directives with data- to be HTML compatible
**@stratusjs/angularjs-extras 0.8.2** published
* Add: directive `fullHeight` given option to enable/disable
=> @stratusjs/idx 0.13.2 @stratusjs/angularjs-extras 0.18.2

packages/angular/package.json, packages/angular/src/base/base.component.ts, packages/angular/src/core/base.interface.ts, packages/angular/src/core/responsive.component.ts, packages/angular/src/core/responsive.interface.ts, packages/angular/src/core/root.component.ts, packages/angular/src/editor/code-view-dialog.component.ts, packages/angular/src/editor/editor.component.ts, packages/angular/src/editor/media-dialog.component.ts, packages/angular/src/media-selector/media-selector-vanilla.component.html, packages/angular/src/media-selector/media-selector.component.html, packages/angular/src/media-selector/media-selector.component.scss, packages/angular/src/media-selector/media-selector.component.ts, packages/angular/src/selector/selector.component.ts, packages/angular/src/test/test.directive.ts, packages/angular/src/tree/tree-dialog.component.ts, packages/angular/src/tree/tree-node.component.ts, packages/angular/src/tree/tree.component.ts
Adds:
- Basic Horizontal Drag & Drop Template
- Basic Horizontal Drag & Drop Styles
- Global Events for Component Bridge Support
- Responsive Component for Redraw with Collision Avoidance
- Responsive Interface for Strict Typing
- Base Interface with UID for Strict Typing
- Image Hover Info with Event Triggers
- Multimedia Support
- SVGs: Data Types & Clear Buttons
- Legacy Design Implementation
Changes:
- ChangeDetectorRef is now Protected instead of Private
- All Components now extend Root or Responsive Component
- Root Component now extends Responsive Component
- CSS Loader: Failures have improved warning messages
- CSS Loader: Failures now throw full error
- Template: Inline Block to Flex
- Template: Various Design Improvements
- Media Selector extends Responsive Component
- Legacy …
=> Angular 0.2.77: Media Selector

packages/angular/package.json, packages/angular/src/core/responsive.component.ts, packages/angular/src/media-selector/media-selector.component.html, packages/angular/src/tree/tree-dialog.component.ts, packages/angular/src/tree/tree-node.component.ts, packages/angular/src/tree/tree.component.ts, packages/angularjs/package.json, packages/angularjs/src/services/model.ts, packages/core/package.json, packages/core/src/datastore/modelBase.ts
Adds:
- `Model`: ChangeSet Debug Options - _Bumps AngularJS & Core Packages_
Changes:
- `ResponsiveComponent`: returns a Promise
- `Media Selector`: Remove Button uses local function
Fixes:
- `Media Selector`: Initial Model Selection on Empty List
=> Angular 0.2.78: Media Selector Fixes

gulpfile.ts, packages/angular/package.json, packages/angular/src/base/base.component.ts, packages/angular/src/confirm-dialog/confirm-dialog.component.ts, packages/angular/src/editor/code-view-dialog.component.ts, packages/angular/src/editor/editor.component.ts, packages/angular/src/editor/media-dialog.component.ts, packages/angular/src/media-selector/media-selector.component.ts, packages/angular/src/selector/selector.component.ts, packages/angular/src/tree/tree-dialog.component.ts, packages/angular/src/tree/tree-node.component.ts, packages/angular/src/tree/tree.component.ts, packages/stripe/package.json
* Fix: gulp compress will no longer lowercase minified html attributes (breaking angular templates)
**@stratusjs/angular 0.2.80** published
* Add: most components will now call for minified html/css
**@stratusjs/stripe 1.0.1** published
* Change: Human readability
=> @stratusjs/angular 0.2.80 @stratusjs/stripe 1.0.1

packages/angular/package.json, packages/angular/src/app.module.ts, packages/angular/src/boot.ts, packages/stripe/package.json, packages/stripe/src/payment-method-item.component.html, packages/stripe/src/payment-method-item.component.less, packages/stripe/src/payment-method-item.component.ts, packages/stripe/src/payment-method-list.component.html, packages/stripe/src/payment-method-list.component.less, packages/stripe/src/payment-method-selector.component.html, packages/stripe/src/payment-method-selector.component.less, packages/stripe/src/payment-method-selector.component.ts, packages/stripe/src/setup-intent.component.ts
**@stratusjs/stripe 1.1.0** published
* Add: PaymentMethodSelector
* Add: PaymentMethodItem (display and control of individual payment methods)
**@stratusjs/angular 0.2.81** published
* Add: New Components above
The addition of the new payment selections via dedicated and reusable components.
=> @stratusjs/stripe 1.1.0 @stratusjs/angular 0.2.81

packages/angular/package.json, packages/angular/src/media-selector/media-selector.component.scss, packages/angular/src/selector/selector.component.scss
=> Angular 0.2.83: Design Fixes

packages/angularjs/package.json, packages/angularjs/src/controllers/generic.ts
=> AngularJS 0.2.54: Hoist `$window` for Generic Controllers

packages/angular/package.json
Changes:
- https://github.com/Sitetheory/stratus/pull/593
Note: This is simply a version bump to bring the new changes live.
=> Angular 0.2.85: Fix Content Selector Tooltip

packages/angular/package.json, packages/angular/src/editor/editor.component.ts
Fixes:
- Editor Media Transform
=> Angular 0.2.86: Fix Editor Media Transform

packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/property/details-sub-section.component.ts, packages/idx/src/property/details.classic.component.html, packages/idx/src/property/details.component.html, packages/idx/src/property/details.component.ts, packages/idx/src/property/list.component.html
- List now also requests non-numeric StreetNumber field (fixing `idx.getStreetAddress()`)
- Added <time> elements to details and details.classic for ADA
- Added missing aria elements to list/details/details.classic template for ADA
- Fix ListingKey/Id supplied (now properly is detected as a string)
- Updated details.classic template to send Address as subject rather than a comment
- Fix details/SubSection on handling blank and empty arrays
- Updated details/details.classic aria for better representation
- Updated package dependencies
=> @stratusjs/idx 0.13.6

packages/angularjs-extras/src/directives/fullHeight.ts, packages/angularjs/package.json, packages/angularjs/src/components/base.ts, packages/angularjs/src/services/collection.ts, packages/core/package.json, packages/core/src/misc.ts, packages/idx/src/idx.ts, packages/idx/src/property/details-sub-section.component.ts
Adds:
- Core: `LooseFunction`
Changes:
- Core: Bump Version to `0.2.23`
- AngularJS: Bump Version to `0.2.56`
Removes:
- Core: `ObjectWithFunctions`
References:
- https://github.com/Sitetheory/stratus/pull/600#discussion_r753599274
=> Core `LooseFunction` (Follow-up for #600)

packages/core/package.json, packages/core/src/datastore/xhr.ts
Changes:
- Fixes XHR requests to properly detect loose object instead of array
=> @stratusjs/core 0.2.25 XHR header setting fix

packages/idx/package.json, packages/idx/src/property/details.classic.component.html, packages/idx/src/property/details.component.html
Changes:
- Fixes moment syntax in the details templates
- Updates dependencies to latest
=> @stratusjs/idx 0.14.2

packages/idx/package.json, packages/idx/src/property/details.classic.component.html
@stratusjs/idx 0.14.3 published
Removes:
- Removes extra Open House aria-labels
=> @stratusjs/idx 0.14.3 ADA fixes

.travis.yml, packages/angular/package.json, packages/angularjs-extras/package.json, packages/angularjs-extras/src/controllers/panel.js
Changes:
- Travis Config Update
- Angular Package Update
- AngularJS-Extras Package Update
=> Angular 0.2.91: Update Dependencies, AngularJS-Extras 0.8.5: Fix Dialog & Panel, & Update Travis

packages/angular/package.json
Follow-up for: https://github.com/Sitetheory/stratus/pull/607
=> Angular 0.2.92: Version Bump

packages/angular/package.json, packages/angular/src/tree/tree-dialog.component.html
=> Angular 0.2.93: Fix Tree Dialog

packages/angularjs/package.json, packages/angularjs/src/services/model.ts
Adds:
- Better Event Timing
Changes:
- `@stratus/angularjs` to `0.2.57`
=> Model: Event Enhancements

packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/member/list.component.ts, packages/idx/src/property/list.component.html, packages/idx/src/property/list.component.less
**@stratusjs/idx 0.14.4 published**
Changes:
- Fixes member search (for mothership subscriptions)
- Navigation button fix for ADA
- fix getStreetAddress() in the cases both Street and UnparsedAddress exist
=> @stratusjs/idx 0.14.6

packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/map/map.component.ts, packages/idx/src/property/list.component.html, packages/idx/src/property/list.component.less
**@stratusjs/idx 0.15.0** published
Adds:
- Go To option for @stratusjs/idx/property/list pagination
Changes:
- Fix AdvancedSearch button from appearing when a url was not provided
- Fix @stratusjs/idx/map timing to boundary focus does not initiate
=> @stratusjs/idx 0.15.0

packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/member/list.component.ts, packages/idx/src/member/mothership/list.selector.component.html, packages/idx/src/member/mothership/list.selector.component.less, packages/idx/src/member/search.component.ts
**@stratusjs/idx 0.15.1 published**
@stratusjs/idx/member
Add:
- add adjustable variableSync + request more fields
Changes:
- list compress area shown
- variableSync fix input detection
=> @stratusjs/idx 0.15.1 - Member changes

packages/idx/package.json, packages/idx/src/idx.ts
*@stratusjs/idx 0.15.2 published*
- getStreetAddress() StreetSuffix  conditional removal (BAREIS change)
=> @stratusjs/idx 0.15.2 - StreetSuffix  conditional removal (BAREIS change)

packages/stripe/package.json, packages/stripe/src/payment-method.component.html, packages/stripe/src/payment-method.component.ts, packages/stripe/src/setup-intent.component.ts
**@stratusjs/stripe 1.1.1** published
Adds:
- add dialog message/info provided from an api
- fix sitetheory new SetupIntent requests
=> @stratusjs/stripe 1.1.1 fix creation + dialog

package.json, packages/idx/package.json, packages/idx/src/property/details.classic.component.html, packages/idx/src/property/details.component.html, packages/map/package.json, packages/map/src/map.component.ts, packages/stripe/package.json, packages/stripe/src/payment-method-selector.component.ts, packages/stripe/src/payment-method.component.html
**@stratusjs/idx 0.15.3** published
Changes:
- renamed VTour to Virtual Tour
- update dependencies (fix map zoomed out and not always calling on resize process)
**@stratusjs/map 0.4.3** published
Changes:
- Move init processes until idle state
- Extra fitBounds() attempts catch possible later marker calls
**@stratusjs/stripe 1.1.2** published
Changes:
- Fix changeset checks on null object
- Fix regex pattern checks on field input
=> @stratusjs/idx 0.15.3 @stratusjs/map 0.4.3 @stratusjs/stripe 1.1.2

packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/property/admin/search.filter.component.html, packages/idx/src/property/details.component.html, packages/idx/src/property/list.component.html, packages/idx/src/property/search.classic.component.html, packages/idx/src/property/search.compact.component.html, packages/idx/src/property/search.component.html
**@stratusjs/idx 0.15.5** published
Adds:
- RDFa identifiers on Property List
- basic RDFa identifiers on Property Details
Changes:
- Updated description wording for Pricing Labels
- Property `where` use `City` as array
=> @stratusjs/idx 0.15.5 Pricing Labels + City as Array + RDFa

.travis.yml, packages/angularjs/package.json, packages/angularjs/src/services/registry.ts
Adds:
- Registry Redraw for Model Errors
Changes:
- Bump `@stratusjs/angularjs` to `0.3.1`
Removes:
- Travis: yarn install
- Travis: NodeJS 14
=> Fix Model Responsiveness & Optimize Travis Config

packages/idx/package.json, packages/idx/src/idx.ts
**@stratusjs/idx 0.15.6** published and hotfixed
Changes:
- Fix City search to be case insensitive
=> @stratusjs/idx 0.15.6 fix City search

packages/idx/package.json, packages/idx/src/property/list.component.ts, packages/idx/src/property/search.component.html
**@stratusjs/idx 0.15.7** published
Changes:
- fix Location Not Showing in Search Area After Entering Manually
=> @stratusjs/idx 0.15.7

packages/angular/package.json, packages/angular/src/editor/editor.component.ts
Adds:
- `allow` attribute to Froala
Changes:
- Bump `@stratusjs/angular` to `0.2.95`
=> Add `allow` attribute to Froala

packages/idx/package.json, packages/idx/src/idx.ts
**@stratusjs/idx** 0.15.8 published
Changes:
- fixes possible empty variables on search request
=> @stratusjs/idx 0.15.8

packages/angularjs/package.json, packages/angularjs/src/services/model.ts, packages/angularjs/src/services/registry.ts
Adds:
- Registry `data-temp` Functionality
- Registry TypeCasting for `data`
Changes:
- Bump `@stratusjs/angularjs` to `0.3.2`
=> Add Registry `data-temp` Functionality

packages/boot/package.json, packages/boot/src/init.js
Adds:
- Boot: Common Extensions
Changes:
- Bump `@stratusjs/boot` to `0.3.1`
=> Boot: Add Common Extensions

packages/angular/package.json, packages/angular/src/tree/tree-dialog.component.html
Changes:
-Bump `@stratusjs/angular` to `0.3.4`
Fixes:
- `iconResourcePath` Accessors in `tree-dialog.component.html`
=> Fix `iconResourcePath` Accessors

packages/angular/package.json, packages/angular/src/media-selector/media-selector.component.ts
Changes:
- Bump `@stratusjs/angular` to `0.3.5`
Fixes:
- Media Selector Responsiveness
=> Fix Media Selector Responsiveness

packages/stripe/package.json, packages/stripe/src/payment-method-selector.component.html, packages/stripe/src/payment-method-selector.component.ts
@stratusjs/stripe 1.2.0 published
Adds:
- Sets payment selection onto field to allow external apps to read
=> @stratusjs/stripe 1.2.0

.gitignore, package.json, packages/angularjs-extras/package.json, packages/angularjs-extras/src/filters/avatar.ts
@stratusjs/angularjs-extras 0.10.0 published
Adds:
- LibrAvatar filter ( | avatar )
Changes:
- Updates/Syncs dependencies with stratusjs
=> @stratusjs/angularjs-extras 0.10.0 Filter/Avatar

packages/angular/package.json, packages/angular/src/backend.service.ts, packages/angular/src/tree/tree-dialog.component.ts
Changes:
-Bump `@stratusjs/angular` to `0.3.6`
Fixes:
- Backend Failure with Unhandled Requests
=> Fix Backend Failure with Unhandled Requests

.gitignore, packages/angularjs/package.json, packages/angularjs/src/services/collection.ts
Changes:
- `collection.filtering` to an evaluation flag
- `collection.paginate` to an evaluation flag
- Bump `@stratusjs/angularjs` to `0.3.4`
- Clean `.gitignore` Config
Fixes:
- `.gitignore` References
=> Improve Collection Flags & `.gitignore` Config

packages/runtime/package.json, packages/runtime/src/stratus.ts
Changes:
- Bump `@stratusjs/runtime` to `0.11.14`
References:
- https://github.com/Sitetheory/stratus/pull/651
=> Bump `@stratusjs/runtime` to `0.11.14`

packages/angular/package.json, packages/angular/src/editor/editor.component.ts, packages/angular/src/editor/link-dialog.component.html, packages/angular/src/editor/link-dialog.component.ts
Adds:
- AutoComplete Workflow
- List View Toggle
Changes:
- Default to AutoComplete Workflow
- Bump `@stratusjs/angular` to `0.3.9`
=> Enhance Froala Link Dialog UI

packages/angular/package.json, packages/angular/src/editor/link-dialog.component.ts, packages/angular/src/froala/plugins/inputButton.ts, packages/angular/src/froala/plugins/linkManager.ts
Adds:
- InputButton Selection API
- LinkManager Proper Insertion
Changes:
- Bump `@stratusjs/angular` to `0.3.10`
=> Enhance InputButton and LinkManager Insertion

packages/angular/src/froala/plugins/inputButton.ts
Fixes:
- `inputButton` EventData Type
=> Fix `inputButton` EventData Type

packages/angular/package.json, packages/angular/src/editor/citation-dialog.component.html, packages/angular/src/editor/citation-dialog.component.scss, packages/angular/src/editor/citation-dialog.component.ts
@stratusjs/angular 0.4.4 published
Changed
- Updated citation dialog wording and add notes for empty titles
=> @stratusjs/angular 0.4.4 Citation Editor Wording

packages/angular/package.json, packages/angular/src/editor/editor.component.ts, packages/angular/src/editor/link-dialog.component.html, packages/angular/src/editor/link-dialog.component.ts, packages/angular/src/froala/plugins/inputButton.ts, packages/angular/src/froala/plugins/linkManager.ts, packages/angular/src/tree/tree-dialog.component.html
Adds:
- `inputButton` Data Triggers
- `link-dialog` Highlighted Node Access
- `link-dialog` Element Hydration
- `link-dialog` Element Form Inputs
- `linkManager` Element Hooks and Input
Changes:
- `tree-dialog` Radio Button Labels
- Bump `@stratusjs/angular` to `0.4.6`
=> @stratusjs/angular 0.4.6: Froala Plugin Enhancements

packages/angular/package.json, packages/angular/src/data/convoy.interface.ts, packages/angular/src/editor/editor.component.ts, packages/angular/src/editor/link-dialog.component.html, packages/angular/src/editor/link-dialog.component.scss, packages/angular/src/editor/link-dialog.component.ts, packages/angular/src/tree/tree-dialog.component.html, packages/runtime/package.json, packages/runtime/src/stratus.ts
Adds:
- `link-dialog` Content Selector AutoComplete Hydration
- `link-dialog` Horizontal Progress Bar for Selected Content
- `link-dialog` Full Width for Material Form Inputs
Changes:
- `convoy.interface.ts` Handle Direct Objects
- `link-dialog` Option Progress Bar to Horizontal
- `tree-dialog` Option Progress Bar to Horizontal
- `runtime` Disable SSO Redirects
- Bump `@stratusjs/angular` to `0.4.7`
- Bump `@stratusjs/runtime` to `0.11.15`
Removes:
- `editor` Built-In Link List Button
- `editor` Built-In Link Editor Reference to new Link Inserter
- `editor` Built-In Link Style Button
=> @stratusjs/angular 0.4.7: Froala Plugin Enhancements | @stratusjs/runtime 0.11.15: Disable SSO Redirects

packages/angular/package.json, packages/angular/src/editor/media-dialog.component.ts
Fixes:
- `media-dialog` Trailing Quote
=> @stratusjs/angular 0.4.10: Fix Media Insert

packages/angularjs/package.json, packages/angularjs/src/services/collection.ts, packages/angularjs/src/services/model.ts, packages/angularjs/src/services/registry.ts
Adds:
- Registry: `data-payload` Support
- Registry: `data-convoy` Support
- Collection: `data-payload` Support
- Collection: `data-convoy` Support
- Model: `data-payload` Support
- Model: `data-convoy` Support
=> @stratusjs/angularjs 0.5.0: data-payload & data-convoy Support

gulpfile.ts, packages/angularjs-extras/src/components/jsonEditor.js, packages/angularjs-extras/src/controllers/panel.js, packages/angularjs-extras/src/directives/domEvents.js, packages/angularjs-extras/src/directives/stringToNumber.js, packages/angularjs-extras/src/loaders/angular.bind.js, packages/boot/src/config.js, packages/boot/src/env.js, packages/boot/src/init.js, packages/runtime/src/stratus.amd.js
Fixes:
- Gulp Standard Linter
- Standard Linter Errors
=> Fix Gulp Standard Linter

packages/runtime/package.json, packages/runtime/src/stratus.ts
Adds:
- Session Sync via XHR
Changes:
- Bump `@stratusjs/runtime` to `0.12.0`
=> @stratusjs/runtime 0.12.0: Add SSO XHR Support

packages/angular/package.json, packages/angular/src/selector/selector.component.ts, packages/angularjs/package.json, packages/angularjs/src/services/collection.ts, packages/core/package.json, packages/core/src/misc.ts, packages/idx/package.json, packages/idx/src/disclaimer/disclaimer.component.ts, packages/idx/src/idx.ts, packages/idx/src/map/map.component.ts, packages/idx/src/member/details.component.ts, packages/idx/src/member/list.component.ts, packages/idx/src/member/search.component.ts, packages/idx/src/office/list.component.ts, packages/idx/src/office/search.component.ts, packages/idx/src/property/details-sub-section.component.ts, packages/idx/src/property/details.component.ts, packages/idx/src/property/list.component.ts, packages/idx/src/property/search.component.ts
Adds:
- @stratusjs/angular/component/selector option to not use `priority`
Changes:
- @stratusjs/angualrjs/collection fix to re-allow for blank collection
-@stratusjs/core/misc/safeUnqiueUid fix join
- IDX refactor
- - Fix member lookupo popup
=> @stratusjs/idx 0.16.0 @stratusjs/angularjs 0.6.2 @stratusjs/angular 0.5.4 @stratusjs/core 0.5.2

gulpfile.ts, package.json, packages/angularjs-extras/package.json, packages/angularjs-extras/src/filters/truncate.ts
Adds:
- `package.json`: design script
Changes:
- Bumps `stratusjs/angularjs-extras` to `0.12.3`
- `gulpfile.ts`: consistent targets and compilation
Fixes:
- Truncate Filter
References:
- https://github.com/Sitetheory/stratus/pull/684
=> @stratusjs/angularjs-extras 0.12.3: Truncate Filter

packages/angular/src/selector/selector.component.html, packages/angular/src/selector/selector.component.scss, packages/angular/src/selector/selector.component.ts
Adds
- Toggle Status to @stratusjs/angular/selector
=> Add ability to toggle status of the Content on the content selector.

packages/angularjs-extras/package.json, packages/angularjs-extras/src/components/citation.scss
@stratusjs/angularjs-extras 0.12.5 published
Changes
- stratus-citation update css to reflect neutral tone
=> @stratusjs/angularjs-extras 0.12.5 fix requested css

packages/angularjs-extras/package.json, packages/angularjs-extras/src/directives/onScreen.ts, packages/angularjs-extras/src/directives/src.ts
@stratusjs/angularjs-extras 0.12.8 published
Changes
- fixes directive removal of direct jquery
=> @stratusjs/angularjs-extras 0.12.8 fix jq removals

packages/angular/package.json, packages/angular/src/editor/editor.component.ts
Adds:
- Editor: Debug flag toggle via cookie
- Editor: `onBlur()` event (triggers `model.set()`)
- Editor: `onFocus()` event
Changes:
- Bump `@stratusjs/angular` to `0.5.6`
Fixes:
- Editor: UI Workflow
=> @stratusjs/angular 0.5.6: Editor Improvements

packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/property/search.component.ts
@stratusjs/idx 0.16.3 published
Adds
- Warning on property/search if search is attempted and not inited
Changes
- Fixes along with the search engine to allow sort by _BestPrice client sided (needed if multiple feeds are used
- Fixes to pull only the very last of requested counts from each feed for proper aggregation
- Fixes for race conditions in feeds returned and sorting
- Fixes property/search:init-now binding
=> @stratusjs/idx 0.16.3 Multiple Feeds and general fixes

packages/angular/package.json, packages/idx/package.json, packages/idx/src/idx.ts, packages/map/package.json, packages/map/src/map.component.ts
@stratusjs/map 0.5.2 published
@stratusjs/idx 0.16.4 published
@stratusjs/angular 0.5.10 published
Adds
- Warnings added to sa-map if invalid json is provided
- Simppe Type adds
Changes
- Fixes changed Sitetheory payload parameters for idx feed requests
=> map 0.5.2 idx 0.16.4 angular 0.5.10

packages/idx/package.json, packages/idx/src/disclaimer/disclaimer.component.ts, packages/idx/src/idx.ts, packages/idx/src/property/details.component.html, packages/idx/src/property/details.component.less, packages/idx/src/property/details.component.ts, packages/idx/src/property/list.component.html, packages/idx/src/property/list.component.less, packages/idx/src/property/list.component.ts, packages/idx/src/property/search.component.ts
@stratusjs/idx 0.16.5 published
Adds
- MLS logo beside IDX/ML number
Changes
- Fixes disclaimer not initing on occasion
- fixes disclaimer showing only correct MLS on details pages
=> @stratusjs/idx 0.16.5

packages/angular/package.json, packages/angular/src/editor/editor.component.ts, packages/angular/src/editor/link-dialog.component.html
Adds:
- `editor`: Codemirror Line Wrapping
Changes:
- `link-dialog`: Hide Empty Link Text
- Bump `@stratusjs/angular` to `0.5.14`
=> @stratusjs/angular 0.5.14: Editor Improvements

packages/angular/package.json, packages/angular/src/app.module.ts, packages/angularjs-extras/package.json, packages/angularjs-extras/src/components/jsonEditor.ts, packages/map/package.json, packages/map/src/map.module.ts, packages/stripe/package.json, packages/stripe/src/stripe.module.ts
@stratusjs/angular 0.6.0 published
Adds:
- StratusPackages for more independent package management
- - added Map and Stripe packages
@stratusjs/map 0.6.0 & @stratusjs/stripe 1.5.0 published
Adds:
- StratusPackages
@stratusjs/angularjs-extras 0.12.10 published
Changes:
- Fixes Json Editor pretty printing https://app.asana.com/0/596117517607240/1203802564547625/f
=> Angular StratusPackages + jsonEditor fix

packages/angular/package.json, packages/angularjs-extras/src/normalizers/angular.exports.js, packages/boot/package.json, packages/boot/src/config.js, packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/property/list.component.html, packages/idx/src/property/list.component.ts
@stratusjs/boot 0.4.0 published
Adds:
- All missing packages paths are added to config.js and boot.dist for external loading
Changes:
- Refactored config.js formatting to sync with platforms
@stratusjs/angular 0.6.2 published
Adds:
- npm installation of required libraries
@stratusjs/idx 0.17.5 published
Changes:
- Fixes to 'nulled' images on property lists
- Fixes missing aria-label complaints
- Typos
=> @stratusjs/boot 0.4.0 @stratusjs/angular 0.6.2 @stratusjs/idx 0.17.5

packages/boot/package.json, packages/boot/src/config.js
@stratusjs/boot 0.4.1 published
Add:
- add missing shims/meta to config
=> @stratusjs/boot 0.4.1 add missing shims/meta

packages/angular/package.json, packages/map/package.json, packages/map/src/map.component.ts, packages/stripe/package.json, packages/stripe/src/payment-method-list.component.html, packages/stripe/src/payment-method-list.component.ts, packages/stripe/src/payment-method-selector.component.html, packages/stripe/src/payment-method-selector.component.ts, packages/stripe/src/payment-method.component.ts, packages/stripe/src/setup-intent.component.ts, packages/stripe/src/stripe.module.ts
@stratusjs/stripe 1.5.2 published
Adds:
- component options for custom Api / Target routes
- component options for PM button wording
Changes:
- fixes usage for list display
@stratusjs/map 0.6.4 published
Changes:
- Disables Marker animations while in Safari (due to css animation bug)
- Fix initialization to render immediately upon loading
@stratusjs/angular 0.6.5 published
Changes:
- @stratusjs/stripe bundled
=> @stratusjs/stripe 1.5.2 @stratusjs/map 0.6.4 @stratusjs/angular 0.6.5

packages/angular/package.json, packages/stripe/package.json, packages/stripe/src/payment-method.component.html, packages/stripe/src/payment-method.component.ts, packages/stripe/src/setup-intent.component.ts
@stratusjs/stripe 1.5.3 published
Changes:
- fix Api options pathing
- fix field ordering
@stratusjs/angular 0.6.6 published
- publish Stripe changes
=> @stratusjs/stripe 1.5.3 @stratusjs/angular 0.6.6

package.json, packages/boot/src/config.ts, packages/idx/package.json, packages/idx/src/property/list.carousel.component.html, packages/idx/src/property/list.carousel.component.less, packages/idx/src/property/list.component.less, packages/idx/src/property/list.component.ts, packages/idx/src/property/list.map.component.html, packages/swiper/package.json, packages/swiper/src/carousel.component.less
@stratusjs/swiper 1.2.1 published
Changes:
- Prevent accidentally highlighting entire slideshow
------
@stratusjs/idx 0.18.1 published
Adds:
- Widget options for custom usage + styling for options
- list.map.component template placeholder for future map usage
Changes:
- Fix stylings that Sitetheory overwrites everywhere
- Various styling additions for widget options and fixes
=> @stratusjs/idx 0.18.1 @stratusjs/swiper 1.2.1

packages/angular/package.json, packages/stripe/package.json, packages/stripe/src/payment-method-item.component.ts, packages/stripe/src/payment-method-list.component.ts, packages/stripe/src/payment-method-selector.component.ts, packages/stripe/src/payment-method.component.ts, packages/stripe/src/setup-intent.component.ts, packages/stripe/src/stripe.service.ts
@stratusjs/stripe 1.5.4 published
Changes:
- Prevent default actions sooner on <button>s
- Fallbacks/reattempts to wait for/load Stripe API
- General updates for consistency
@stratusjs/angular 0.6.7 published
Changes:
- @stratusjs/stripe compiled
=> @stratusjs/stripe 1.5.4 @stratusjs/angular 0.6.7

packages/idx/package.json, packages/idx/src/property/details.component.less, packages/idx/src/property/list.carousel.component.html, packages/idx/src/property/list.carousel.component.less
@stratusjs/idx/ 0.18.2 published
Changes:
- Fix property/list.carousel commas with no address
- Fix property/list.carousel icon spacing
- Fix property/list.carousel image css various sizing
- Fix property/details css various sizing
=> @stratusjs/idx/ 0.18.2

packages/idx/package.json
@stratusjs/idx 0.18.3 published
Changes
- Updates dependancies
- Publishing changes from #718
=> @stratusjs/idx 0.18.3

packages/angularjs/package.json, packages/angularjs/src/services/collection.ts
Adds:
- `Collection.clearTemp()`
Changes:
- Bump `@stratusjs/angularjs` to `0.6.3`
=> @stratusjs/angularjs 0.6.3: Add `Collection.clearTemp()`

packages/angular/package.json, packages/angular/src/core/root.component.ts, packages/angular/src/editor/editor.component.ts
Adds:
- JSON Attributes
- Custom Froala Classes
Changes:
- Bump `@stratusjs/angular` to `0.7.0`
=> @stratusjs/angular 0.7.0: Add JSON Attributes & Custom Froala Classes

packages/angular/package.json, packages/angular/src/editor/link-dialog.component.html, packages/angular/src/editor/link-dialog.component.ts
Changes:
- Bump `@stratusjs/angular` to `0.7.1`
Fixes:
- Hidden Link Text Field
=> @stratusjs/angular 0.7.1: Fix Hidden Link Text Field

packages/idx/package.json, packages/idx/src/property/list.component.less
@stratusjs/idx 0.18.6 published
Changes:
- Additions from #726 compiled and published
- Fixed invalid // from stylesheet
=> @stratusjs/idx 0.18.6

packages/angular/package.json, packages/map/package.json, packages/map/src/map.component.ts
@stratusjs/map 0.6.5 published
Changes
- fix fullHeight sizing checks when Array is directly provided
@stratusjs/angular 0.7.2 published
Map changes bundled and published
=> @stratusjs/angular 0.7.2 @stratusjs/map 0.6.5

packages/angular/package.json, packages/angular/src/tree/tree-dialog.component.ts
Changes:
- Bump `@stratusjs/angular` to `0.7.4`
Fixes:
- Tree Dialog Queries
=> @stratusjs/angular 0.7.4: Fix Tree Dialog Queries

packages/angularjs/package.json, packages/angularjs/src/services/model.ts
Changes:
- Update `meta.get()` Functionality
Fixes:
- Fatal on Malformatted Meta
=> AngularJS 0.6.4: Meta Improvements

packages/core/package.json, packages/core/src/datastore/modelBase.ts
Adds:
- `_.get()` to `ModelBase`
=> Core 0.6.0: Model Improvements

packages/core/package.json, packages/core/src/datastore/modelBase.ts
Adds:
- `toPatch()`: property removals to changesets
=> Core 0.6.1: Model Patch Improvements

packages/angularjs/package.json, packages/angularjs/src/services/model.ts
Fixes:
- Inaccurate Error Status on Missing Meta
=> AngularJS 0.6.5: Model Meta Fix

packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/property/admin/search.filter.component.html, packages/idx/src/property/list.component.html, packages/idx/src/property/list.component.ts, packages/idx/src/property/search.classic.component.html, packages/idx/src/property/search.compact.component.html, packages/idx/src/property/search.component.html, packages/idx/src/property/search.component.ts
@stratusjs/idx 0.20.1 published
Changes:
- Force use of eLocation instead of Location
- Fixed UrlLoad parameters allow nulling a field
- Fixed Search UrlLoad allow remove ending /
- Fixed Listing UrlLoad allow remove ending /
- Fixed Office searches
- Fixed Filter counts and clearing all
=> @stratusjs/idx 0.20.1

packages/angular/package.json, packages/angular/src/tree/tree-node.component.html, packages/angular/src/tree/tree.component.scss
Adds:
- Better Design
Fixes:
- Inaccurate Drag & Drop Boxes
- Hover Box Visible while Dragging
- Hover Box Disappearing during Hover
=> Angular 0.8.0: Tree Redesign

packages/angularjs/package.json, packages/angularjs/src/services/model.ts
=> AngularJS 0.6.6: Fix Model Status

packages/angularjs/package.json, packages/angularjs/src/services/collection.ts, packages/angularjs/src/services/model.ts
Adds:
- Status Check for Collections
Changes:
- Streamlines Payload Handling
Fixes:
- Payload Status
=> AngularJS 0.6.7: Fix Payload Status

packages/angular/package.json, packages/angular/src/tree/tree-node.component.html, packages/angular/src/tree/tree.component.scss, packages/angular/src/tree/tree.component.ts
Adds:
- Async/Await Drop Event Timing
- UI Refresh after Model Save
- Cookie Toggle for Node Borders
- Cookie Toggle for Debug Data
Changes:
- Require `@stratusjs/core` of `^0.6.2`,
Fixes:
- Drop Border Visible after Drop
=> Angular 0.8.1: Tree Refinements

packages/angular/package.json, packages/angular/src/tree/tree.component.ts
Adds:
- Collection Event for UI Rebuild on Save
=> Angular 0.8.2: Tree Timing

packages/angularjs/package.json, packages/angularjs/src/controllers/generic.ts
Adds:
- [Controller Generic] Scroll Functionality
=> AngularJS 0.7.0: Scroll Functionality

packages/angularjs/package.json, packages/angularjs/src/controllers/generic.ts
Adds:
- `delay` Parameter
- Full Documentation
Changes:
- `inUrl` defaults to `false`
Removes:
- Debug Logs
=> AngularJS 0.7.1: Scroll Functionality

packages/idx/package.json, packages/idx/src/property/admin/search.filter.component.html, packages/idx/src/property/search.component.html, packages/idx/src/property/search.component.less, packages/idx/src/property/search.component.ts
@stratusjs/idx 0.21.0 published
property/search
Adds:
- Additional preset Location filters moved to a popover block
Changes:
- Renames various classes for proper description
- Hides OtherFilter indictors with Location filter indicator is shown
- Fixes missing `eCity` field in admin
=> @stratusjs/idx 0.21.0

packages/angular/package.json, packages/angular/src/editor/editor.component.ts, packages/angular/src/froala/plugins/linkManager.ts, packages/core/src/environment.ts
Changes:
- [LinkManager] Disable Quick Edit Button
=> Angular 0.8.3: Disable Link Quick Edit Button

packages/angular/package.json, packages/angular/src/media-selector/media-selector.component.html, packages/angular/src/media-selector/media-selector.component.scss
Fixes:
- Media Drag Placeholder
=> Angular 0.8.4: Fix Media Drag Placeholder

packages/angularjs/package.json, packages/angularjs/src/services/collection.ts, packages/angularjs/src/services/model.ts
Changes:
- Model/Collection process meta.success instead of meta.status
=> @stratusjs/angularjs 0.9.0

packages/angular/package.json, packages/angular/src/tree/tree-dialog.component.html, packages/angular/src/tree/tree-dialog.component.ts
=> Angular 0.8.5: Fix Tree Checkbox

packages/calendar/src/calendar.less, packages/idx/src/property/list.component.less, packages/idx/src/property/search.component.html
@stratusjs/calendar unpublished
Changes
- Removes 'custom' background color from day grids
- Removes default background color from pager button
=> Fixes to Calendar colors

packages/calendar/package.json, packages/idx/package.json
@stratusjs/calendar 1.3.1 published
@stratusjs/idx 0.21.3 published
Changes
- published changes from https://github.com/Sitetheory/stratus/pull/762
=> @stratusjs/calendar 1.3.1 @stratusjs/idx 0.21.3

packages/angularjs-extras/package.json, packages/angularjs-extras/src/filters/luxon.ts
@stratusjs/angularjs-extras/luxon 0.14.1 published
Changes
- fix default time formatting
=> @stratusjs/angularjs-extras/luxon 0.14.1 fix default time formatting

packages/idx/package.json, packages/swiper/package.json, packages/swiper/src/carousel.component.less
@stratusjs/swiper 1.2.3 published
Changes:
- Fix Swiper in Firefox
- Update Dependencies
@stratusjs/idx 0.21.4 published
Changes:
- Update Dependencies
=> @stratusjs/swiper 1.2.3 Fix Swiper in Firefox @stratusjs/idx 0.21.4

packages/angular/package.json, packages/stripe/package.json, packages/stripe/src/payment-method-item.component.less, packages/stripe/src/payment-method-list.component.html, packages/stripe/src/payment-method-list.component.less, packages/stripe/src/payment-method-list.component.ts
@stratusjs/angular 0.9.2 published
- Stripe package update
@stratusjs/stripe 1.9.0
Add
- payment-method-list addCardDisabled option
Changes
- fix hidden elements on Payment Lists
=> @stratusjs/angular 0.9.2 @stratusjs/stripe 1.9.0

packages/angularjs-extras/package.json, packages/angularjs-extras/src/filters/luxon.ts
@stratusjs/angularjs-extras 0.14.2 published
Changes:
- fix default luxon formatting
=> @stratusjs/angularjs-extras 0.14.2

packages/angularjs-extras/package.json, packages/angularjs-extras/src/filters/luxon.ts, packages/angularjs/package.json, packages/angularjs/src/services/collection.ts, packages/angularjs/src/services/model.ts, packages/angularjs/src/services/registry.ts
@stratusjs/angularjs-extras 0.14.3 published
Changes:
- Luxon provide local timezone if null
@stratusjs/angularjs 0.9.1 published
Changes:
- fix collection cache to prevent accidentally altering cache history
- services lodash refactor and clean up
=> @stratusjs/angularjs 0.9.1 @stratusjs/angularjs-extras 0.14.3

packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/property/list.component.ts, packages/idx/src/property/search.component.ts
@stratusjs/idx 0.23.0 published
Adds:
- apiVersion requests to all search/auth queries
- Status + Price and Status + Recent sort options
=> @stratusjs/idx 0.23.0

packages/angularjs/package.json, packages/angularjs/src/services/collection.ts, packages/angularjs/src/services/model.ts
Adds:
- `Model` Data Attribute for Headers
- `Collection` Data Attribute for Headers
- `Collection` Properly Extend Options
- `Collection` `this.sanitizeOptions()`
- `Collection` `withCredentials` Option
=> AngularJS 0.9.2: Custom Header Support

packages/core/package.json, packages/core/src/misc.ts
@stratusjs/core 0.7.1 published
Changes:
- fix patch() ignoredKeys checks
=> @stratusjs/core 0.7.1

packages/angularjs/package.json, packages/angularjs/src/services/collection.ts
Removes:
- Collection Sanitize Options on Construct
Fixes:
- Collection Options outside of Whitelist
=> AngularJS 0.9.4: Fix Collection Options

packages/angular/package.json, packages/angular/src/selector/selector-autocomplete.component.html, packages/angular/src/selector/selector.component.html, packages/angular/src/selector/selector.component.ts
@stratusjs/angular 0.10.1 published
Changes
- angular/selector use getString to ensure only string or null returns
=> @stratusjs/angular 0.10.1 angular/selector string fixes

packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/property/details-sub-section.component.html, packages/idx/src/property/details-sub-section.component.ts, packages/idx/src/property/details.component.ts
**@stratusjs/idx 0.24.0** published
Adds:
- sub-details: adds options: html, hideName options
- details: add fields ConcessionsAmount, ConcessionsPercent, ConcessionsComments
Changes:
-  fix parseInt typing complaints
- converted fetchReplaceModel to async
=> @stratusjs/idx 0.24.0

packages/angularjs/package.json, packages/angularjs/src/services/model.ts
Fixes:
- [Model] Duplicate Save XHRs
=> AngularJS 0.10.1: Fix Duplicate XHRs

packages/runtime/package.json, packages/runtime/src/stratus.ts
Changes:
- Disable SSO by Default
=> Runtime 0.14.0: Disable SSO by Default

packages/angular/src/media-selector/media-selector.component.html, packages/idx/src/property/list.component.less
@stratusjs/angular
Changes:
- `<sa-media-selector>` adds class `common-selector-styles`
@stratusjs/idx
Changes:
- `<stratus-idx-property-list>` adjusts image opacity
=> Fixes to media library component styling

packages/runtime/package.json, packages/runtime/src/stratus.ts
Changes:
- Disable SessionSync
=> Runtime 0.14.1: Disable SessionSync

packages/angular/package.json, packages/angular/src/editor/link-dialog.component.ts
Fixes:
- `link-dialog` Context
=> Angular 0.12.4: Fix `link-dialog` Context

packages/angular/package.json, packages/angular/src/editor/editor.component.ts
Adds:
- Froala `token` Support
=> Angular 0.12.5: Add Froala `token` Support

packages/angularjs-extras/src/filters/luxon.ts, packages/idx/package.json, packages/idx/src/property/details.component.html
@stratusjs/idx 0.24.3  published
Changes
- Added idx AgentDetails even if missing name (so long as there is a license)
=> @stratusjs/idx 0.24.3 AgentDetails

packages/angularjs-extras/package.json, packages/angularjs-extras/src/filters/luxon.ts
@stratusjs/angularjs-extras 0.17.1 publish
Changes:
- Fix luxon filter attempting to process null inputs. Will now just return raw input
=> @stratusjs/angularjs-extras 0.17.1 luxon filter fixes

packages/angularjs-extras/package.json, packages/angularjs-extras/src/directives/href.ts, packages/angularjs-extras/src/directives/tabRouting.ts, packages/core/package.json, packages/core/src/misc.ts, packages/idx/package.json, packages/idx/src/disclaimer/disclaimer.component.ts, packages/idx/src/idx.ts, packages/idx/src/listTrac.ts, packages/idx/src/map/map.component.ts, packages/idx/src/member/details.component.ts, packages/idx/src/member/list.component.ts, packages/idx/src/member/search.component.ts, packages/idx/src/office/list.component.ts, packages/idx/src/office/search.component.ts, packages/idx/src/property/details.component.ts, packages/idx/src/property/list.component.ts
**@stratusjs/core 0.9.0 published**
Adds:
- hashBang unified functionality `getHashBangParam`, `setHashBangParam`
------
**@stratusjs/angularjs-extras 0.18.0 published**
Changes:
- tabRouting directive - replace $location logic with hashBang functionality
- href directive - replace $location logic with native javascript
------
**@stratusjs/idx 0.25.0 published**
Changes:
- replace $location logic with hashBang functionality
Removes:
- all unneeded imports and logic
=> @stratusjs/core 0.9.0 @stratusjs/angularjs-extras 0.18.0 @stratusjs/idx 0.25.0 $location updates

packages/angular/package.json, packages/angular/src/tree/tree.component.scss, packages/angular/src/tree/tree.component.ts
Fixes:
- Tree Drag & Drop Functionality
- Tree Placeholder Display
=> Angular 0.12.6: Fix Drag & Drop

packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/property/details.component.ts
@stratusjs/idx 0.26.0 published
Adds
- includes MLSAreaMinor in searches
- includes MLSAreaMinor in details pages
=> @stratusjs/idx 0.26.0 MLSAreaMinor

packages/angular/package.json, packages/angular/src/tree/tree.component.ts
Fixes:
- Tree Drag & Drop Functionality
=> Angular 0.12.7: Fix Drag & Drop

packages/angular/package.json, packages/angular/src/tree/tree.component.ts
Fixes:
- Tree Drag & Drop Functionality
=> Angular 0.12.9: Fix Drag & Drop

packages/angular/package.json, packages/angular/src/tree/tree.component.ts
Fixes:
- Tree Drag & Drop Functionality
=> Angular 0.12.10: Fix Drag & Drop

packages/angularjs-extras/package.json, packages/angularjs-extras/src/components/jsonEditor.html, packages/angularjs-extras/src/components/jsonEditor.ts
Changes
- jsonEditor fix values not initing
=> @stratusjs/angularjs-extras 0.18.1

package.json, packages/calendar/package.json, packages/calendar/src/iCal.ts, packages/idx/src/idx.ts
@stratusjs/calendar 1.6.1 published
Changes
- Updates/locks ical.js to 2.1.0
- Refactored ICal typings for latest version
- - https://github.com/kewisch/ical.js/compare/v2.0.1...v2.1.0
@stratusjs/idx
Changes
- Fix linting checks for unknown to typed variables
=> @stratusjs/calendar 1.6.1

packages/idx/package.json, packages/idx/src/property/admin/search.filter.component.html, packages/idx/src/property/search.component.ts
@stratusjs/idx 0.27.0 published
Adds
- allow Street Address input for searching in admin
Changes
- Updates Stratus Dependencies to latest
=> @stratusjs/idx 0.27.0

packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/property/search.component.ts
@stratusjs/idx 0.27.2 published
Changes
- Fix - Remove double slash (/) when search opens a new page
Removes
- Remove odd console.log
=> @stratusjs/idx 0.27.2

packages/angularjs-extras/package.json, packages/angularjs-extras/src/filters/luxon.ts
- Updates to luxon.ts (implementing language locale option)
=> [v0.9.1] Update @angularjs-extras to "0.18.2" - Luxun update

packages/core/package.json, packages/core/src/misc.ts
- misc.ts detect changes to elements and order of strings in an array, when calculating change set
=> Update Stratus Core 0.9.2

packages/angular/package.json, packages/stripe/package.json, packages/stripe/src/payment-method-item-display.component.ts, packages/stripe/src/payment-method-item.component.html, packages/stripe/src/payment-method-item.component.less, packages/stripe/src/payment-method-item.component.ts
- @stratus/core 0.9.2 -- detect changes to elements and order of strings in an array
- @stratusjs/stripe 2.0.1 -- show 'deleted' on cards deleted
- @stratusjs/angular 0.12.13 -- require updates
=> Update packages: Stripe, Core, Angular

packages/angular/package.json, packages/stripe/package.json, packages/stripe/src/payment-method-selector.component.html, packages/stripe/src/payment-method-selector.component.less, packages/stripe/src/payment-method-selector.component.ts
@stratusjs/stripe 2.1.0 published
Adds:
- allow Deselecting Payment Method
@stratusjs/angular 0.12.14 published 
Changes:
- Updated for @stratusjs/stripe 2.1.0
=> @stratusjs/stripe 2.1.0 @stratusjs/angular 0.12.14 allow Deselecting Payment Method
