Sitetheory/stratus

packages/angular/package.json, packages/angularjs/package.json, packages/angularjs/src/services/collection.ts, packages/angularjs/src/services/model.ts, packages/angularjs/src/services/registry.ts, packages/core/package.json, packages/core/src/datastore/modelBase.ts, packages/core/src/datastore/xhr.ts, packages/core/src/errors/errorBase.ts, packages/core/src/events/aether.ts, packages/core/src/events/chronos.ts, packages/core/src/events/eventBase.ts, packages/core/src/events/eventManager.ts, packages/runtime/package.json, packages/runtime/src/stratus.ts
- Multiple New Versions and Comprehensive Code
=> Stabilize Packages

gulpfile.js, packages/idx/package.json, packages/idx/src/member/details.component.ts, packages/idx/src/member/list.component.ts, packages/idx/src/member/search.component.ts, packages/idx/src/property/details-sub-section.component.ts, packages/idx/src/property/details.component.html, packages/idx/src/property/details.component.ts, packages/idx/src/property/list.component.html, packages/idx/src/property/list.component.less, packages/idx/src/property/list.component.ts, packages/idx/src/property/search.component.ts, packages/swiper/package.json, packages/swiper/src/carousel.js
- Fixed gulp min file mangling
- Corrected file pathing for local templates/css, library css, and images
- Fixed template design issues
Known Issues:
- When the swiper is minified, is is unable to use the function `camelToSnake` and breaks.
=> @stratusjs/idx 0.3.3 @stratusjs/swiper 0.0.4

packages/idx/package.json, packages/idx/src/property/details.classic.component.html, packages/idx/src/property/details.component.html, packages/idx/src/property/details.component.ts, packages/idx/src/property/list.component.html, packages/idx/src/property/list.component.ts, packages/idx/src/property/search.component.html, packages/idx/src/property/search.component.ts, packages/swiper/package.json, packages/swiper/src/carousel.component.ts
- list widget use `query` parameter (options <--> query backwards compatible)
- details widget fixed to use property title in SFAR
- search widget fixed URL load of ListingType selection
- fixed  Swiper the bad css path again (not found due to env conflicts)
- fixed details.classic variable call
=> @stratusjs/idx 0.3.8 @stratusjs/idx 0.1.2

packages/idx/package.json, packages/idx/src/property/details.component.html, packages/idx/src/property/details.component.ts, packages/idx/src/property/list.component.html, packages/idx/src/property/list.component.ts, packages/swiper/package.json, packages/swiper/src/carousel.component.html, packages/swiper/src/carousel.component.ts
idx and swiper use stratus-src to lazy load Sitetheory images
Known Issue:
stratus-src seems to be having issues with swiper, probably due to the way that swiper relies on knowing the size of the image it's loading to initially set, yet stratus-src changes the image after the image already loads.
The effect: the image shown could be mucher smaller, as it was the original image size (results not consistent because load times can vary)
=> @stratusjs/swiper 0.1.6 @stratusjs/swiper 0.3.16

packages/angularjs-extras/package.json, packages/angularjs-extras/src/directives/src.js, packages/idx/package.json, packages/idx/src/property/details.component.html, packages/idx/src/property/details.component.less, packages/idx/src/property/details.component.ts, packages/idx/src/property/list.component.html, packages/idx/src/property/list.component.less, packages/runtime/package.json, packages/runtime/src/stratus.ts, packages/swiper/README.md, packages/swiper/package.json, packages/swiper/src/carousel.component.html, packages/swiper/src/carousel.component.ts
**@stratusjs/angularjs-extras 0.3.3**
* Added `stratus-src-load` for variable Progressive image loading on certain resources
* Updated Dependencies (fixes stratus-src image loading invalid urls with ImageLoad())
**@stratusjs/idx 0.3.18**
* Fix invalid } in Contact Url
* Updated SlideImage types and provide lazy parameter
* Corrected templates to progressive stratus-src loading
* Moved CSS to LESS files
**@stratusjs/runtime 0.10.6**
* Fix Stratus.Internals.LoadImage to only upgrade image size AFTER it is prefetched and loads correctly. (fixes stratus-src loading)
**@stratusjs/swiper 0.1.7**
* 'lazy' parameter in SlideImages allows swiper to replicate stratus-src to find the large images before initializing (progressive loading disabled as it breaks swiper)
* Updated instructions. Swiper …
=> @stratusjs/angularjs-extras 0.3.3 @stratusjs/idx 0.3.18 @stratusjs/runtime 0.10.6 @stratusjs/swiper 0.1.7

packages/angularjs-extras/package.json, packages/calendar/package.json
This caused a mistake of publishing the calendar package to @stratusjs/angularjs-extras 0.0.1 version
=> @stratusjs/angularjs-extras @stratusjs/calendar fix publishing mistakes

packages/angularjs-extras/package.json, packages/angularjs-extras/src/directives/src.js, packages/idx/package.json, packages/idx/src/property/details.component.html, packages/idx/src/property/list.component.html
@stratusjs/angularjs-extras 0.4.3
* Rename `stratus-src-load` to `stratus-src-version`
* `stratus-src="false"` will now prevent stratus-src from doing anything
@stratusjs/idx 0.3.24
* MLS Widget polishes published
* Idx List and Details updated to use `stratus-src-version`
=> @stratusjs/angularjs-extras 0.4.3 @stratusjs/idx 0.3.24

packages/angular/src/tree/tree.component.ts, packages/angularjs/src/services/model.ts
This ensures the collection handles the change from a model save with event bubble.
=> Fix Model Save Propagation for Collections

packages/idx/package.json, packages/idx/src/idx.ts
**@stratusjs/idx** 0.4.4
* change admin filter to specific City
* Fixed undefined issue with PostalCode/AreaId, added central location to add array/other items that need to be initialized (to try and prevent it again)
* Fixed Neighborhoods not searching correctly for MLSAreaMajor
restrict andOr to it's requested type (preparing for array searches)
* Add UnparsedAddress
* Remove AreaId
* Add hidden filter fields on front end if set in backend.
* added or fixed stringLikeArray, stringIncludesArray, andOr{ stringEquals, stringLike, stringLikeArray, stringIncludesArray}
* refactor the query compilation script
this PR adds
* update comments
* added or fixed stringLikeArray, stringIncludesArray, andOr{ stringEquals, stringLike, stringLikeArray, stringIncludesArray}
* refactor the query …
=> @stratusjs/idx 0.4.4

packages/idx/src/idx.ts, packages/idx/src/property/admin/search.filter.component.html, packages/idx/src/property/details.component.ts, packages/idx/src/property/list.component.ts, packages/idx/src/property/search.component.html, packages/idx/src/property/search.component.ts
@stratusjs/idx
* Fixed data association between widget files (the $scope are now given strict types)
* Refactored List, Search, and Idx service to provide strict Types and properly pass on the -correct- variable types instead of assuming what is what.
*  Fixed the admin page and allowing more control of the query being passed around (https://app.asana.com/0/1154407311832843/1156345571542394/f)
Will probably need to add more variables, but for the moment, the large part is out of the way
This is not published and still has many console.logs
=> @stratusjs/idx data association and service fixes

packages/angularjs/package.json, packages/angularjs/src/services/collection.ts, packages/angularjs/src/services/model.ts, packages/core/package.json, packages/core/src/misc.ts
Changes:
- Disable Cache by Default on Collections
- Force Full Payload on New Model Save
- Force Model.handleChanges() trigger after XHR Complete
- AngularJS 0.2.21: Bump Package Version
- Core 0.2.14: Move Model.Flatten() to Misc
Fixes:
- ID and Version Change Detection when persisting a new entity
- Saving of a new entity (we want the whole model, not just the patch for initial saves)
- List Caches giving inaccurate results (especially during pagination of changing entities)
=> Collection & Model: Various Improvements

packages/angularjs-extras/package.json, packages/angularjs-extras/src/directives/domEvents.js, packages/angularjs-extras/src/filters/toArray.js
**@stratusjs/angularjs-extras** 0.6.0
* **domEvents** Directives to easily add missing dom events that were not published with angularjs currently
* * Adds 'focusin' and 'focusout' (as focus and blur do not accomplish this)
* Add missing angular dependency for toArray Filter
=> @stratusjs/angularjs-extras 0.6.0 domEvents

gulpfile.js, package.json, packages/angularjs/package.json, packages/angularjs/src/services/collection.ts, packages/angularjs/src/services/model.ts, packages/angularjs/src/services/registry.ts
Changes (Repo):
- Add Key Transformer to TypeScript
Changes (AngularJS 0.2.25):
- Better Model Controls
- Better Collection Controls
- Dynamic Data Attributes
- Bump AngularJS Version to 0.2.25
=> AngularJS 0.2.25: Better Model Controls

gulpfile.js, packages/angular/package.json, packages/angular/src/app.module.ts, packages/angular/src/editor/code-view-dialog.component.html, packages/angular/src/editor/code-view-dialog.component.scss, packages/angular/src/editor/code-view-dialog.component.ts, packages/angular/src/editor/editor.component.ts, packages/angular/src/editor/quill-input-button.plugin.ts
Adds:
- Code View Dialog
Fixes:
- Nullified fields
- Universal Button
- Dialog Separation
Note: This dialogs don't save yet, but they are able
to be previewed in a dev environment.
=> Angular 0.2.25: Functional Quill Buttons

packages/angularjs-extras/src/components/jsonEditor.html, packages/angularjs-extras/src/components/jsonEditor.js, packages/angularjs-extras/src/components/jsonEditor.less
NOTE: this could not be tested because today jsonEditor won't load from stratus, because it's got a bad path somehow.
=> convert inline styles to CSS classes

packages/idx/package.json, packages/idx/src/property/list.component.ts
**@stratusjs/idx 0.7.7** published
* property/list default detailsLinkUrl to self reference
* fix List Map marker updates (async call now awaiting)
=> @stratusjs/idx 0.7.7

.travis.yml, packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/map.component.ts, packages/idx/src/member/details.component.ts, packages/idx/src/member/list.component.ts, packages/idx/src/member/search.component.ts, packages/idx/src/property/details.classic.component.html, packages/idx/src/property/details.component.html, packages/idx/src/property/details.component.ts, packages/idx/src/property/list.component.html, packages/idx/src/property/list.component.ts, packages/idx/src/property/search.component.ts
**@stratusjs/idx 0.7.9** published
* Adds option to preferrably use the terms "Closed", "Sold/Leased", or "Sold/Rented"
* Remove deprecated `getUid()`
* Remove unused imports
**config**
* Travis fixes
=> @stratusjs/idx 0.7.9

packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/member/list.component.ts, packages/idx/src/member/search.component.ts, packages/idx/src/property/admin/search.filter.component.html, packages/idx/src/property/list.component.ts, packages/idx/src/property/search.component.ts
**@stratusjs/idx 0.7.12** published
* Search widget use emit/on to Fix List and Search connection
* fix service 0 from being unselectable 
* Force only at least 1 and only 1 service (at this time)
* fix order variables being inconsistent and clearing when searching in admin
=> @stratusjs/idx 0.7.12

packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/property/admin/search.filter.component.html, packages/idx/src/property/details.classic.component.html, packages/idx/src/property/details.component.html, packages/idx/src/property/search.compact.component.html, packages/idx/src/property/search.component.html
**@stratusjs/idx 0.8.5** published
* listTrac analytics variable renamed to listTrac to match with provided services in Sitetheory api
* Broken HTML doc fixes
* Prevent "Openhouses Only" option if no additional filters are provided
* Temporary VirtualOpenHouse labels for MLSs that require them (only MLSL at this time)
=> @stratusjs/idx 0.8.5

packages/angular/package.json, packages/angular/src/confirm-dialog/confirm-dialog.component.html, packages/angular/src/editor/editor.component.html, packages/angular/src/editor/editor.component.ts, packages/angular/src/selector/selector.component.html, packages/angular/src/tree/tree-dialog.component.html, packages/angular/src/tree/tree-node.component.html, packages/angular/src/tree/tree.component.html, packages/angular/src/tree/tree.nested.component.html
Changes:
- `<button>` to `<a>`
Fixes:
- Button triggers when `enter` is pressed in any form field
=> Angular 0.2.46: Fix Button Submissions

packages/idx/package.json
Temporarily reverted gulp compress settings used to publish to allow property .min.css files in this package. This does not affect future `gulp compress` or `npm publish` abilities.
=> @stratusjs/idx 0.9.1

.gitignore, packages/angularjs-extras/package.json, packages/angularjs-extras/src/filters/numeral.ts, packages/idx/package.json, packages/idx/src/map/map.component.ts, packages/idx/src/property/search.component.html, packages/idx/src/property/search.component.ts
**@stratusjs/idx 0.9.5** published
* change: Map component: markers use better abbreviation and reused method
* fix: Search component: 'enter' on Price input causes Search
* fix: Search component: empty prices are removed from search (fixes url and bad max searches)
* fix: Search component: allow Search price up to 9,999,999
* fix: typos
**@stratusjs/angularjs-extras 0.8.0** published
* feature: numeral Filter
=> @stratusjs/idx 0.9.5 @stratusjs/angularjs-extras 0.8.0

.gitignore, packages/idx/package.json, packages/idx/src/property/list.component.html, packages/idx/src/property/list.component.ts, packages/idx/src/property/search.component.less, packages/idx/src/property/search.component.ts
**@stratusjs/idx 0.9.6** published
* fix: price popup invisibly blocking List/sorting
* change: sort renamed 'Highest Price'/'Lowest Price'
* change: standardize and convert OrderOptions
* feature: Sort options label name after current selection
* feature: selectively display OrderOptions
**Stratus**
* fix: gitignore typo
=> @stratusjs/idx 0.9.6 - Ordering Changes

packages/idx/package.json, packages/idx/src/disclaimer/disclaimer.component.ts, packages/idx/src/idx.ts, packages/idx/src/map/map.component.ts, packages/idx/src/member/details.component.html, packages/idx/src/member/details.component.ts, packages/idx/src/member/list.component.html, packages/idx/src/member/list.component.less, packages/idx/src/member/list.component.ts, packages/idx/src/member/mothership/list.selector.component.html, packages/idx/src/member/mothership/list.selector.component.less, packages/idx/src/member/search.component.ts, packages/idx/src/property/details.classic.component.html, packages/idx/src/property/details.classic.component.less, packages/idx/src/property/details.component.html, packages/idx/src/property/details.component.less, packages/idx/src/property/details.component.ts, packages/idx/src/property/list.component.html, packages/idx/src/property/list.component.less, packages/idx/src/property/list.component.ts, packages/idx/src/property/search.component.ts
**stratusjs/idx 0.11.0** published
* Added: stratus-idx-proeprty-list `init-now` option to delay initialization
* Added: stratus-idx-disclaimer
* Changed: Moved all Disclaimer references to use widget for ease and to avoid duplication
* Changed stratus-idx-member widgets to make use of OfficeMlsId for standardized Office searches
=> stratusjs/idx 0.11.0

packages/idx/package.json, packages/idx/src/disclaimer/disclaimer.component.ts, packages/idx/src/idx.ts, packages/idx/src/property/list.component.html, packages/idx/src/property/list.component.less, packages/idx/src/property/list.component.ts
**@stratusjs/idx 0.11.1** published
* @stratusjs/idx/disclaimer add options
* * `init-now` for delaying initialization until models are ready
* * `hide-on-duplicate` to disable widget when there one already on the screen
* @stratusjs/idx/property/list add option
* * `hide-disclaimer` option to remove the disclaimer for the bottom of the list of one exists on the page already
=> @stratusjs/idx 0.11.1

packages/idx/package.json, packages/idx/src/disclaimer/disclaimer.component.less, packages/idx/src/disclaimer/disclaimer.component.ts, packages/idx/src/idx.ts, packages/idx/src/map/map.component.ts, packages/idx/src/member/details.component.ts, packages/idx/src/member/list.component.ts, packages/idx/src/member/search.component.ts, packages/idx/src/property/details.component.ts, packages/idx/src/property/list.component.html, packages/idx/src/property/list.component.less, packages/idx/src/property/list.component.ts, packages/idx/src/property/search.component.ts
**@stratusjs/idx 0.12.1** published
* Changed: Idx service's on Emitters now manage each event with a unqiueId and running the return method after `on()` will allow deleting events (removes watchers from repeating forever)
* Add: Service tokens now supply list of each service's logos and fetchTimes at session start
* Changed: Each Idx service disclaimer handled separately for better control
* Changed: All Idx Disclaimer logos are now to bottom for future use to allow better side by side layout
* Fix: Correctly handle the Idx's required fetchTime
* Fix: Corrected styling escaping stratus-idx-property-list, all styling has been recontained and nested within
**Known Issues**
* Stratus widgets don't remove themselves from memory when no longer on DOM. E.g. an element may be removed and …
=> @stratusjs/idx 0.12.1

packages/idx/src/property/search.component.html, packages/idx/src/property/search.component.ts
options: "location", "basic", "advanced"
add option to show a link to the advanced search (used on modules that embed this component)
Add option to show advanced search link on list component as well (needed if there is no search bar)
=> add options to specify which search filters to show

packages/idx/src/property/list.component.html, packages/idx/src/property/list.component.ts, packages/idx/src/property/search.component.html, packages/idx/src/property/search.component.ts
@apocist these components need the init-now option in order to make sure the attribute values are working when model is loaded.
=> Add option to pass in filter options, advanced search button

packages/idx/package.json, packages/idx/src/disclaimer/disclaimer.component.less, packages/idx/src/idx.ts, packages/idx/src/property/list.component.less, packages/idx/src/property/list.component.ts, packages/idx/src/property/search.component.html, packages/idx/src/property/search.component.less, packages/idx/src/property/search.component.ts
**@stratusjs/idx 0.12.9** unpublished
* changed prevent search if query has not changed
* added throttle query attempts
* added hide the clear button if editing location to prevent double search attempts
* added remaining function types to search/list
* fix Incorrectly Displaying in Url Without City/Location
* fix prevent search if collection is not done loading
* fix logo container accounting bounding box
* fix StyleLint errors
Version contains https://github.com/Sitetheory/stratus/pull/572
=> @stratusjs/idx 0.12.9 unpublished

packages/idx/src/property/admin/search.filter.component.html, packages/idx/src/property/list.component.ts
I noticed there were two and that's not right
=> Remove Duplicate `displayOrderOptions` Definition and Allow Multiple Data Feeds

packages/angular/package.json, packages/angular/src/base/base.component.ts, packages/angular/src/confirm-dialog/confirm-dialog.component.ts, packages/angular/src/editor/code-view-dialog.component.ts, packages/angular/src/editor/editor.component.ts, packages/angular/src/editor/media-dialog.component.html, packages/angular/src/editor/media-dialog.component.ts, packages/angular/src/media-selector/media-selector-vanilla.component.html, packages/angular/src/media-selector/media-selector.component.html, packages/angular/src/media-selector/media-selector.component.ts, packages/angular/src/media-selector/media-selector.horizontal.component.html, packages/angular/src/selector/selector-autocomplete.component.html, packages/angular/src/selector/selector.component.html, packages/angular/src/selector/selector.component.ts, packages/angular/src/test/test.directive.ts, packages/angular/src/tree/tree-dialog.component.html, packages/angular/src/tree/tree-dialog.component.ts, packages/angular/src/tree/tree-node.component.html, packages/angular/src/tree/tree-node.component.ts, packages/angular/src/tree/tree.component.ts, packages/angularjs/src/components/base.ts, packages/map/package.json, packages/map/src/map.component.ts
Adds:
- Angular: Add Dynamic Install Path
- Angular & Map: Localized `Stratus` References for Templates
Changes:
- Angular: Bump to `0.2.84`
- Map: Bump to `0.4.1`
- Angular & Map: Use `Stratus.BaseUrl` instead of hard-coded locations
- AngularJS: Use Template Strings (Bump Unnecessary)
Removes:
- Media Selector: Empty Message
=> Dynamic Install Paths & Media Selector Improvements

packages/idx/package.json, packages/idx/src/disclaimer/disclaimer.component.ts, packages/idx/src/idx.ts, packages/idx/src/property/details-sub-section.component.html, packages/idx/src/property/details-sub-section.component.ts, packages/idx/src/property/details.classic.component.html, packages/idx/src/property/details.classic.component.less, packages/idx/src/property/details.component.html, packages/idx/src/property/details.component.less, packages/idx/src/property/details.component.ts, packages/idx/src/property/list.component.html, packages/idx/src/property/list.component.less, packages/idx/src/property/list.component.ts, packages/idx/src/property/search.classic.component.html, packages/idx/src/property/search.component.html
published for pre-release
- Added required Listing Credit to the top of `details`
- Added required Listing Credit to the top of `details.classic`
- Added now unused `getWebsiteMainContact()` to `IDX` service for quick reference
- Added basic Accessibility to common idx widgets
- - Updated image shapeholders
- - ADA added to property/`details-sub-section`
- - ADA added to property `search` / `search.classic` (just simple items, needs more testing)
- - ADA added to property/`list`
- - - Pagination fixes
- - - Dialog popups labels
- - - Listed property items
- - ADA compatibility and navigation added to property `details` / `details.classic`
- - - `details.classic` given missing contact variables and functionality from modern versions
- - ADA added to property/`disclaimer`
- Fix `contact` …
=> @stratusjs/idx 0.14.0 Listing Credit/ADA

packages/idx/package.json, packages/map/package.json, packages/swiper/package.json
Changes:
- Updates dependencies of swiper and idx to prevent old @stratusjs modules from installing (e.g. this was force installing @stratusjs/angularjs-extras 0.3.0 installing its now incompatible modules)
- Updates map to latest stratus dependencies
=> Fix  swiper and idx dependency issues

packages/swiper/package.json, packages/swiper/src/carousel.component.html, packages/swiper/src/carousel.component.ts
Adds:
- Add Component Typings
Changes:
- Swiper upgraded to version 7.3.1 to include a number of accessibility improvements
- Adjust options to account for new version
- Improved angular template to only process ng-ifs once before foreachs
=> @stratusjs/swiper 1.1.0 Swiper upgraded to 7.3.1

packages/angularjs-extras/package.json, packages/angularjs-extras/src/directives/jsonToObject.ts
@stratusjs/angular-extras 0.9.0 published
Adds:
- new directive `stratus-json-to-object` for holding json on html render and maintaining object on model
=> @stratusjs/angular-extras 0.9.0

packages/calendar/package.json, packages/calendar/src/calendar.ts
**@stratusjs/calendar 1.0.2 published**
Adds:
- @stratusjs/calendar attempts to use CORS proxy for added ics files
=> @stratusjs/calendar 1.0.2 use CORS proxy

packages/angularjs-extras/package.json, packages/angularjs-extras/src/directives/bindHtml.ts
Adds:
- `bindHtml` Deep Compilation
- `bindHtml` Compile on `DOMSubtreeModified`
- `bindHtml` can now be a decorator with `ng-bind-html`
Changes:
- Bump `@stratusjs/angularjs-extras` to `0.9.2`
=> Add `bindHtml` Deep Compilation

packages/angularjs-extras/package.json, packages/angularjs-extras/src/directives/bindHtml.ts
Adds:
- Checks to avoid Duplicate Compilations
Changes:
- Throttle to `250ms`
- Selectors from JQuery to Native DOM
- Bump `@stratusjs/angularjs-extras` to `0.9.4`
Removes:
- Tree-Builder for Deep Compilation
=> Optimize Execution for `bindHtml`

packages/angular/src/selector/selector.component.html, packages/runtime/src/stratus.ts
- [Bug] - In Stratus repo fix a bug in the selector component where the best image wouldn't show if the model has a video (bad logic). The best image should always show, but we just want to only show the stratus-src lazy loading if it's not a third party service, e.g. [attr.data-stratus-src]="!_.get(selectedModel, 'version.bestImage.service') ? true : false"
=> BUG - make best image show in selector.component in edge cases where there is video

packages/calendar/package.json, packages/calendar/src/calendar.ts
@stratusjs/calendar 1.0.3 published
Changes:
- Adds additional rendering increments for initial calendar display
- Updates dependencies to sync with stratus + fix header issue
=> @stratusjs/calendar 1.0.3

packages/angularjs/package.json, packages/angularjs/src/services/collection.ts, packages/angularjs/src/services/model.ts, packages/runtime/package.json, packages/runtime/src/stratus.ts
Changes:
- Bump `@stratusjs/angularjs` to `0.3.3`
- Bump `@stratusjs/runtime` to `0.11.11`
Removes:
- Unnecessary Environment IP Reference
Fixes:
- TypeCasting for AngularJS Model/Collection
=> Minor Fixes for `@stratusjs/angularjs` and `@stratusjs/runtime`

packages/runtime/src/stratus.ts
Fix  bug so that we load the `data-stratus-src-spy` so that collapsed before/after images load right size
=> Lazy Loading right size based on parent `data-stratus-src-spy` for collapsed elements

packages/core/package.json, packages/core/src/dom.ts, packages/runtime/package.json, packages/runtime/src/stratus.ts
@stratusjs/core 0.3.1 published
@stratusjs/runtime 0.11.13 published
Adds:
- Adds Select and Selectors to DOM namespace
Changes:
- shifts Select/Select usage to DOM namespace (keeps back support)
- Type usage on Stratus.DOM namespace
=> @stratusjs/core 0.3.1 @stratusjs/runtime 0.11.13 DOM functionality

packages/angularjs/package.json, packages/angularjs/src/services/collection.ts
@stratusjs/angularjs 0.3.6 published
Adds:
- `complete`/`error` on/trigger events for collections (avoid filtering through change events)
=> @stratusjs/angularjs 0.3.6 add collection on/trigger events

packages/idx/src/property/search.component.ts
make listLinkUrl use advancedSearchUrl if it's not set
=> fix IDX search.component.ts bug with watcher when options.query is not yet defined

packages/angularjs/package.json, packages/angularjs/src/services/model.ts, packages/core/package.json, packages/core/src/datastore/xhr.ts
Adds:
- `xhr` Send() Type Casting
- `xhr` Support for `withCredentials`
- `model` Support for `withCredentials`
Changes:
- Bump `@stratusjs/angularjs` to `0.4.0`
- Bump `@stratusjs/core` to `0.4.0`
=> @stratusjs/angularjs & core 0.4.0: XHR Enhancements

packages/angular/package.json, packages/angular/src/editor/editor.component.ts, packages/angular/src/froala/plugins/linkManager.ts, packages/angularjs/package.json, packages/angularjs/src/controllers/generic.ts
Adds:
- `linkManager` Functional Button for Link Edits
Changes:
- `generic` setUrlParams hoisted without modifications
- Bump `@stratusjs/angular` to `0.4.8`
- Bump `@stratusjs/angularjs` to `0.4.1`
=> @stratusjs/angular 0.4.8 & @stratusjs/angularjs 0.4.1: Link Manager & Generic Controller Enhancements

packages/idx/package.json, packages/idx/src/disclaimer/disclaimer.component.ts, packages/idx/src/idx.ts, packages/idx/src/map/map.component.ts, packages/idx/src/member/details.component.ts, packages/idx/src/member/list.component.ts, packages/idx/src/member/search.component.ts, packages/idx/src/office/list.component.ts, packages/idx/src/office/search.component.ts, packages/idx/src/property/details-sub-section.component.ts, packages/idx/src/property/details.component.ts, packages/idx/src/property/list.component.ts, packages/idx/src/property/search.component.ts, packages/stripe/package.json, packages/stripe/src/payment-method-selector.component.ts
@stratusjs/idx 0.15.11 published
Changes:
- Fixes search widget with no list checking for query changes before redirecting https://app.asana.com/0/348823217261712/1203353777771861
- Fixes search widget URL parameters used when redirecting page with "possibly" default ones https://app.asana.com/0/348823217261712/1203353777771862
@stratusjs/stripe 1.3.2 published
Adds:
- Allows option to disable the selector from being changed
Note:
This also published a  missed change from #661
=> @stratusjs/idx 0.15.11 @stratusjs/stripe 1.3.2

packages/angularjs-extras/package.json, packages/angularjs-extras/src/components/citation.html, packages/angularjs-extras/src/components/citation.scss, packages/angularjs-extras/src/components/citation.ts, packages/angularjs-extras/src/directives/baseNew.ts, packages/angularjs-extras/src/directives/bindHtml.ts
@stratusjs/angularjs-extras 0.12.4 published
Adds
- stratus-bind-html options to allow safer logic/data added directly to stratusHtmlBind attribute
- stratus-citation popup @media query for mobile use
Changes
- stratus-citation Add initializer and prevent transcluding elements before ready
- stratus-bind-html fix data compiled if used in conjunction with ng-bind-html (will add delay for race conditions)
- stratus-bind-html added warnings on page if ng-bind-html is used
Notes
Rather than performing logic such as 
`data-stratus-bind-html data-ng-bind-html="::getHTML(model.data.version.text)"`
should now be
`data-stratus-bind-html="::model.data.version.text"`
This will be safer to avoid race conditions and faster as will happen as soon as ready.
=> @stratusjs/angularjs-extras 0.12.4

dist-names.sh, packages/angular/package.json, packages/angular/src/editor/code-mirror-bridge.ts, packages/angular/src/editor/editor.component.ts, packages/angularjs-extras/package.json, packages/angularjs-extras/src/filters/truncateHtml.ts, packages/core/src/misc.ts
Adds:
- `CodeMirrorBridge`: Stratus Initialization
- `CodeMirrorBridge`: `on()` Event Listeners
- `CodeMirrorBridge`: `setSize()` Function
- `CodeMirrorBridge`: `toTextArea()` (Destroy) Function
- `Editor`: `htmlAllowedEmptyTags` with Stratus Components
- `truncateHtml`: filter that preserves html
Changes:
- Bump `@stratusjs/angular` to `0.5.5`
- Bump `@stratusjs/angularjs-extras` to `0.12.6`
- `CodeMirror`: enabled with `codemirror` cookie
- `CodeMirror`: minimalSetup while testing
Removes:
- Core: Deprecation for `truncate()`
Fixes:
- POSIX Standards for `dist-names.sh`
=> @stratusjs/angular 0.5.5: Editor Improvements

packages/angularjs-extras/package.json, packages/angularjs-extras/src/directives/baseNew.ts, packages/angularjs-extras/src/directives/drag.ts, packages/angularjs-extras/src/directives/drop.ts, packages/angularjs-extras/src/directives/fullHeight.ts, packages/angularjs-extras/src/directives/href.ts, packages/angularjs-extras/src/directives/jsonToObject.ts, packages/angularjs-extras/src/directives/masonry.ts, packages/angularjs-extras/src/directives/maxLength.ts, packages/angularjs-extras/src/directives/onScreen.ts, packages/angularjs-extras/src/directives/parentClass.ts, packages/angularjs-extras/src/directives/src.ts, packages/angularjs-extras/src/directives/stringToNumber.ts, packages/angularjs-extras/src/directives/timestampToDate.ts, packages/angularjs-extras/src/directives/trigger.ts, packages/angularjs-extras/src/directives/validate.ts
@stratusjs/angularjs-extras 0.12.7 published
Changes
- Fixes undefined this references in jsonToObjects
- Defaulting to angular defined JQ references
- Sync directives templates/refactor
=> @stratusjs/angularjs-extras 0.12.7 Directive fixes

package.json, packages/angular/package.json, packages/angular/src/editor/code-mirror-bridge.ts, packages/angular/src/editor/editor.component.scss, packages/angular/src/editor/editor.component.ts
Adds:
- CodeMirror: Dark Mode
- Froala: Dark Mode
Changes:
- Editor: CodeMirror from Minimal to Full Featured
- Editor: CodeMirror to Display by Default
- CodeMirrorBridge: DOM Variable
Changes:
- Bump `@stratusjs/angular` to `0.5.8`
Fixes:
- Editor: CodeMirror Display out of Code View
=> @stratusjs/angular 0.5.8: CodeMirror Integration

packages/angular/package.json, packages/angular/src/editor/link-dialog.component.ts, packages/angular/src/froala/plugins/inputButton.ts
Adds:
- inputButton: `restore` event
Changes:
- Bump `@stratusjs/angular` to `0.5.11`
Fixes:
- Editor: Cursor/Selection lost during Link Creation
- Editor: Cursor/Selection lost during Link Dialog Cancellation
=> @stratusjs/angular 0.5.11: Fix Link Dialog

packages/idx/package.json, packages/idx/src/property/list.component.html, packages/idx/src/property/list.component.less
@stratusjs/idx 0.16.6 published
Changes
- @stratusjs/idx Style fixes to IDX component pager buttons from https://github.com/Sitetheory/stratus/pull/699
Notes
- @danielameyer your commit wasn't signed/secure so it wouldn't ever be able to be pulled in, so we've added that here
=> @stratusjs/idx 0.16.6 implement mls-logo fixes

packages/angular/package.json, packages/idx/package.json, packages/idx/src/map/map.component.ts, packages/map/package.json, packages/map/src/map.component.ts, packages/map/src/map.module.ts, packages/stripe/package.json, packages/stripe/src/stripe.module.ts, rollup.config.js
@stratusjs/Idx 0.17.0
Added:
- Bundling now to idx.bundle.js
Changes:
- Updated map component sa-map `callback` pathing due to Stratus being removed from global window
--------
@stratusjs/map 0.6.1 published
Changes:
- Fixes missing ngModules
- Allow checking `callback` paths within `Stratus.Instances` directly (fixes checks in @stratusjs/idx not being in global window anymore)
--------
@stratusjs/stripe 1.5.1 published
Changes:
- Fixes missing ngModules
------
@stratusjs/angular 0.6.1 published the @stratusjs/map + @stratusjs/stripe
=> @stratusjs/Idx bundling + @stratusjs/map + @stratusjs/stripe fix missing modules

packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/property/details.component.ts, packages/idx/src/property/search.component.html
@stratusjs/idx 0.17.1 published
Adds
- `SubdivisionName` search options
- `SubdivisionName` to the combined OR queries of `Location` and `Neighborhood`
Changes
- Adjust "Advanced Search" button to only attempt normal redirect+search action when there is no list currently loaded
- Reordered Details list for location
=> @stratusjs/idx 0.17.1

packages/idx/package.json, packages/idx/src/property/admin/search.filter.component.html, packages/idx/src/property/search.compact.component.html
@stratusjs/idx 0.17.2 published
Adds:
- `Neighborhood` usable Field
Changes:
- existing `MLSAreaMajor` field relabeled, deprecated, and hidden unless used
=> @stratusjs/idx 0.17.2

packages/angular/package.json, packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/map/map.component.ts, packages/idx/src/property/admin/search.filter.component.html, packages/idx/src/property/list.component.ts, packages/map/package.json, packages/map/src/map.component.ts
@stratusjs/map 0.6.2 published
Changes:
- Adjustments to force Google Maps to init when it doesn't finish loading (to display Google specific errors)
@stratusjs/idx 0.17.4 published
Removes:
- LT test file from bundler (to avoid separate _LT undefined complaints)
- CountyOrParish from neighborhood searches
- Multiple Feed disclaimer from the admin filter setup template (as multiple feeds should be fine now)
@stratusjs/angular 0.6.2 published
Notes:
- Re-bundled and published with latest @stratusjs/map
=> @stratusjs/map 0.6.2 @stratusjs/idx 0.17.4 @stratusjs/angular 0.6.2 

packages/angularjs-extras/package.json, packages/angularjs-extras/src/directives/src.ts, packages/boot/package.json, packages/boot/src/config.ts, packages/calendar/package.json, packages/calendar/src/calendar.ts, packages/calendar/src/iCal.ts
**@stratusjs/boot 1.0.1** published
Changes
- Removed unused packages (or those pre-bundled)
-----
**@stratusjs/angularjs-extras** 0.12.12
Changes
- Fixes stratus-src referencing false or null URLs. Will not set `src` if empty
----
**@stratusjs/calendar 1.2.1** published
Changes
- Updated codebase to use the modern framework schema
- Typed
- Fix missing 'recurring' 'nonrecurring' events by adding extra checks in case invalid ICS formatting is provided
Notes
- The Google ICS file had been provided some malformed events by having it's recurrence-id self reference it's own event. We are now forcibly ignoring a recurrence when the Start time matches the recurrence
=> @stratusjs/boot 1.0.1 @stratusjs/angularjs-extras 0.12.12 @stratusjs/calendar 1.2.1

packages/angularjs-extras/package.json, packages/angularjs-extras/src/directives/timestampToDate.ts
@stratusjs/angularjs-extras 0.12.13 published
Changes
- stratus-timestamp-to-date allow removing/blanking out a date to save instead of 0 (allowing subscriptions to un-cancel)
=> @stratusjs/angularjs-extras 0.12.13

packages/angularjs-extras/package.json, packages/angularjs-extras/src/components/citation.scss, packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/member/search.component.ts, packages/idx/src/property/details.component.html, packages/idx/src/property/details.component.less, packages/idx/src/property/list.carousel.component.html, packages/idx/src/property/list.carousel.component.less, packages/idx/src/property/list.component.html, packages/idx/src/property/list.component.less, packages/idx/src/property/list.component.ts, packages/idx/src/property/search.component.html, packages/idx/src/property/search.component.less, packages/idx/src/property/search.component.ts
@stratusjs/angularjs-extras 0.12.14 published
Changes
- Auto Counter(non-custom title) now are the only titles with period prepended https://sitetheory.slack.com/archives/CUE5R9E21/p1681910770841149 
--------
@stratusjs/idx 0.18.4 published
Adds
- Neighborhoods/Offices/Agents to more filters for contorl https://app.asana.com/0/348823217261712/1204300726933726
- Note "no-results" and location input when "Other Filters" are enabled https://app.asana.com/0/348823217261712/1204300726933726
Changes
- property Carousel Fixes
- property Carousel Movement of MLS details to bottom of slides https://app.asana.com/0/596117517607240/1204421091310911
- property list/carousel/details mls credits sizing and alignments https://app.asana.com/0/596117517607240/1204421091310911
- property search fix …
=> @stratusjs/angularjs-extras 0.12.14 @stratusjs/idx 0.18.4 published

packages/idx/package.json, packages/idx/src/idx.ts
@stratusjs/idx@0.18.5 published
Changes:
- When OrderBy 'Status' is used, properly renames to `_Status` to match custom name usage (Fixes `Status` sorting)
=> @stratusjs/idx@0.18.5 OrderBy fixes

packages/angular/package.json, packages/stripe/package.json, packages/stripe/src/payment-method-item-display.component.ts, packages/stripe/src/payment-method-item.component.less, packages/stripe/src/stripe.module.ts
@stratusjs/stripe 1.6.0
Adds
- sa-stripe-payment-method-item-display
- - Specific Wrapper for sa-stripe-payment-method-item for display payment methods in universal way
Changes
- css Width limit on sa-stripe-payment-method-item to prevent "stretching" in certain instances
-----
@stratusjs/angular 0.7.3
- Recompile + Publish Stripe
=> @stratusjs/stripe 1.6.0 @stratusjs/angular 0.7.3

packages/angular/package.json, packages/stripe/package.json, packages/stripe/src/payment-method-item-display.component.ts, packages/stripe/src/payment-method-item.component.html, packages/stripe/src/payment-method-item.component.ts, packages/stripe/src/payment-method-list.component.html, packages/stripe/src/payment-method-list.component.less, packages/stripe/src/payment-method-list.component.ts, packages/stripe/src/payment-method-selector.component.html, packages/stripe/src/payment-method-selector.component.less, packages/stripe/src/payment-method-selector.component.ts, packages/stripe/src/payment-method.component.ts, packages/stripe/src/setup-intent.component.ts, packages/stripe/src/stripe.service.ts
**@stratusjs/stripe 1.7.0 published**
Adds
* Pub/sub on/emit trigger a system
* payment-method-list
* * Add usable 'just' a list for display without selection
* payment-method-selector
* * auto-select any newly added payment methods
* * add progress bar
* payment-method-item
* * add card payment deletion path option (urlRoot)
Changes
* payment-method-selector
* * if no Cards to display, use add button instead
* * close select box on add/remove so it may update
* * refetch latest pms after a delete
* * label the current method better
* * disable card if it was deleted but still in the system
* consolidated reused items throughout
------
**@stratusjs/angular 0.7.5 published**
* Published last stripe changes
=> @stratusjs/stripe 1.7.0 @stratusjs/angular 0.7.5

packages/angularjs-extras/package.json, packages/angularjs-extras/src/directives/tabRouting.ts, packages/angularjs/package.json, packages/backend/package.json, packages/boot/package.json, packages/boot/src/config.ts, packages/calendar/package.json, packages/core/package.json, packages/map/package.json, packages/runtime/package.json
General
Changes:
- Removed yarn from future builds for npm
@stratusjs/angularjs-extras 0.13.0
Adds:
- stratus-tab-routing directive
- - md-tabs url routing functionality
Video Example:
[![Watch the video](https://cdn-cf-east.streamable.com/image/egidt5-screenshot570390.jpg)](https://streamable.com/egidt5)
@stratusjs/boot 1.1.0
Adds:
- stratus-tab-routing directive config
=> @stratusjs/angularjs-extras 0.13.0 @stratusjs/boot 1.1.0 stratus-tab-routing

packages/core/package.json, packages/core/src/datastore/modelBase.ts
Fixes:
- Setting Object to `null` in `modelBase.toPatch()` returns Object with all values of `undefined`
=> Core 0.6.2: Fix `modelBase.toPatch()`

packages/angularjs/package.json, packages/angularjs/src/services/collection.ts, packages/angularjs/src/services/model.ts
Adds:
- Model: Controls for Toast Messages
- Model: Notes for Fixing `this.status`
- Collection: Controls for Toast Messages
- Collection Models: Dissemination of Toast Controls
Fixes:
- Model: Chained Promises
- Model: `throw` in `catch`
- Collection: Chained Promises
- Collection: `throw` in `catch`
=> AngularJS 0.7.2: Fix Promise and Error Handling

packages/idx/package.json, packages/idx/src/idx.ts, packages/idx/src/property/details.classic.component.html, packages/idx/src/property/details.component.html, packages/idx/src/property/list.carousel.component.html, packages/idx/src/property/list.component.html
**@stratusjs/idx 0.21.2 published**
Adds:
- BathroomsHalf and BathroomsThreeQuarter to requested data fields
- BathroomsThreeQuarter to List and Details templates
Changes:
- Deprecating MLSAreaMajor as many MLSs are
=> @stratusjs/idx 0.21.2

package.json, packages/angularjs/package.json, packages/angularjs/src/services/collection.ts, packages/angularjs/src/services/model.ts, rollup.config.js
Adds:
- Toastify Messages
- Toast Error Messages
Changes:
- Enable Model Toast by Default
- Enable Collection Toast by Default
Removes:
- Collection `$mdToast` Messages
- Collection `angular-material` Dependency
- Collection `getInjector()` Workaround
- Model `$mdToast` Messages
- Model `angular-material` Dependency
Fixes:
- Collection Toast Messages
- Model Toast Messages
=> AngularJS 0.8.0: Fix Toast Messages

packages/boot/package.json, packages/boot/src/config.ts
**@stratusjs/boot** 1.2.0 published
Adds
- Boot paths for `<stratus-angularjs-boot/>` (AngularJs Extras), `<stratus-calendar-boot/>`, `<stratus-idx-boot/>`, and `<stratus-swiper-boot/>`
-  - Having these elements on the start of a page will at least load the respective bundles and allow dynamic loading later
=> @stratusjs/boot 1.2.0 Manual Boot Up paths

packages/angular/package.json, packages/angular/src/timezone-selector/timezone-selector.component.html, packages/angular/src/timezone-selector/timezone-selector.component.ts
@stratusjs/angular 0.9.1 published
Changes
- timezone-selector include local time labelling
=> @stratusjs/angular 0.9.1 timezone-selector include local time labelling

packages/angular/package.json, packages/angular/src/core/responsive.component.ts
@stratusjs/angular 0.9.3 published
changes:
- Increasingly delay the refresh loop timeout to avoid cases of component never finishing
=> @stratusjs/angular 0.9.3

packages/angularjs/package.json, packages/angularjs/src/services/collection.ts, packages/angularjs/src/services/model.ts
Changes:
- [Model] Server Errors send only to Console in Production
- [Collection] Server Errors send only to Console in Production
=> AngularJS 0.9.3: Suppress Server Errors

packages/angularjs-extras/package.json, packages/angularjs-extras/src/filters/luxon.ts
@stratusjs/angularjs-extras/luxon 0.14.4 published
Changes:
- fix time inputs of now and API::NOW
- fix unix time not parsing fromSeconds due to now used
=> @stratusjs/angularjs-extras/luxon 0.14.4

packages/angularjs-extras/package.json, packages/angularjs-extras/src/filters/luxon.ts
@stratusjs/angularjs-extras 0.15.1 published
Changes:
- fix Luxon error on parsing 'undefined'
=> @stratusjs/angularjs-extras 0.15.1

packages/angular/package.json, packages/angular/src/selector/selector.component.html, packages/angular/src/selector/selector.component.ts, packages/angular/src/tree/tree-dialog.component.html, packages/angular/src/tree/tree-dialog.component.ts, packages/angular/src/tree/tree-node.component.ts, packages/angular/src/tree/tree.component.ts, packages/angularjs/package.json, packages/angularjs/src/services/model.ts, packages/core/package.json, packages/core/src/misc.ts
@stratusjs/core 0.8.0 published
Adds:
- add serializeUrlParams() to reuse Model functionality
@stratusjs/angularjs 0.10.0 published
Changes:
- Model.destroy() and Model.sync() make use of supplied/meta options to pass needed functionality
- Moved Model.serialize() moved to @stratusjs/core/misc as serializeUrlParams()
@stratusjs/angular 0.10.0 published
Changes:
- sa-selector.toggleStatus(): make use of the needed meta/context of the parent
=> @stratusjs/core 0.8.0 @stratusjs/angularjs 0.10.0 @stratusjs/angular 0.10.0

packages/angular/src/tree/tree-dialog.component.ts, packages/angularjs-extras/package.json, packages/angularjs-extras/src/directives/src.ts, packages/angularjs-extras/src/filters/moment.ts
@stratusjs/angularjs-extras 0.15.2 published
Adds
- `stratus-src` add all "common" web-base image types (apng, avif, webp)
- Missing Dependencies (lodash)
Changes
- Deprecates Stratus.Filters.Moment
- Formatting fix for (purely typing standards)
- Updates all local dependencies to latest
=> @stratusjs/angularjs-extras 0.15.2 add file types for stratus-src

packages/angularjs-extras/package.json, packages/angularjs-extras/src/components/deprecated-reference/selector-deprecated-reference.js, packages/angularjs-extras/src/directives/masonry.ts, packages/angularjs-extras/src/loaders/angular.bind.js, packages/angularjs/package.json, packages/angularjs/src/components/base.ts, packages/angularjs/src/controllers/generic.ts, packages/angularjs/src/directives/base.ts, packages/angularjs/src/injector.ts, packages/angularjs/src/services/collection.ts, packages/angularjs/src/services/model.ts, packages/angularjs/src/services/registry.ts, packages/core/package.json, packages/core/src/environment.ts, packages/runtime/package.json, packages/runtime/src/stratus.ts
**@stratusjs/runtime 0.13.0** published
Adds:
- Stratus.Internals.Cookie() reference for older implementations
Removes:
- Inaccessible deprecated underscore references
**@stratusjs/core 0.8.1** published
Changes:
- modernized formatting
**@stratusjs/angularjs 0.11.0** published
Adds:
- cookie to Generic controller scope
Changes:
- update deprecated underscore mixins
- modernized formatting
**@stratusjs/angularjs-extras 0.16.0** published
Changes:
- update deprecated underscore mixins
=> Fix references to deprecated underscore mixins

packages/angular/src/tree/tree-dialog.component.ts, packages/runtime/src/stratus.ts
**@stratusjs/runtime** unpublished
Removes:
- Removes now fixed Android specific css/js loading logic
**@stratusjs/angular/tree** unpublished
Changes:
- Set fetching limit from 20 to 100 for more results
=> [Bug] Fix android bug on js and css loader (for 5 year old bug hack)

packages/angular/package.json, packages/runtime/package.json, packages/runtime/src/stratus.ts
**@stratusjs/runtime 0.14.3** published
Changes:
- Update JS/CSS loader to follow Stratus Event workflow
- Update current dependencies
Removes:
- Removes now fixed Android specific css/js loading logic
-----
**@stratusjs/angular 0.12.12** published
Changes:
- Tree dialog Set fetching limit from 20 to 100 for more results
- Update current dependencies
Changes published from https://github.com/Sitetheory/stratus/pull/810
=> @stratusjs/runtime 0.14.3 @stratusjs/angular 0.12.12

packages/idx/package.json, packages/idx/src/property/admin/search.filter.component.html, packages/idx/src/property/search.classic.component.html, packages/idx/src/property/search.compact.component.html
@stratusjs/idx 0.26.1 to be published
Changes:
- Contract is a valid status and should be toggle-able independently of other status (e.g. don't need active checked)
=> @stratusjs/idx 0.26.1 make IDX search component allow searching status of "contract"

packages/idx/package.json, packages/idx/src/property/list.component.html
@stratusjs/idx 0.27.1 published
Changes
- Fix Featured Property Images when loaded into a fixed height container
- - force all images to load without stratus-spy due to not being detected as a scroll event to auto load
=> @stratusjs/idx 0.27.1 Fix Featured Property Images

packages/angularjs-extras/package.json, packages/angularjs-extras/src/directives/tabRouting.ts
@stratusjs/angularjs-extras 0.18.3 published
Changes:
- Fixes Tab routing adding an extra '/' delimiter
=> @stratusjs/angularjs-extras 0.18.3
